using System.Text.Json.Serialization;

namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class AccountMove
{
    public virtual object campaign_id { get; set; }
    public virtual object source_id { get; set; }
    public virtual object medium_id { get; set; }
    public virtual string sequence_prefix { get; set; }
    public virtual long sequence_number { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual string access_url { get; set; }
    public virtual string access_token { get; set; }
    public virtual string access_warning { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }

    [JsonPropertyName("ref")]
    public virtual string ref_ { get; set; }

    public virtual string date { get; set; }
    public virtual string state { get; set; }
    public virtual string move_type { get; set; }
    public virtual bool is_storno { get; set; }
    public virtual object journal_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual long[] line_ids { get; set; }
    public virtual object payment_id { get; set; }
    public virtual object statement_line_id { get; set; }
    public virtual object statement_id { get; set; }
    public virtual object tax_cash_basis_rec_id { get; set; }
    public virtual object tax_cash_basis_origin_move_id { get; set; }
    public virtual long[] tax_cash_basis_created_move_ids { get; set; }
    public virtual bool always_tax_exigible { get; set; }
    public virtual string auto_post { get; set; }
    public virtual string auto_post_until { get; set; }
    public virtual object auto_post_origin_id { get; set; }
    public virtual bool hide_post_button { get; set; }
    public virtual bool to_check { get; set; }
    public virtual bool posted_before { get; set; }
    public virtual long[] suitable_journal_ids { get; set; }
    public virtual string highest_name { get; set; }
    public virtual bool made_sequence_hole { get; set; }
    public virtual bool show_name_warning { get; set; }
    public virtual string type_name { get; set; }
    public virtual string country_code { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual bool restrict_mode_hash_table { get; set; }
    public virtual long secure_sequence_number { get; set; }
    public virtual string inalterable_hash { get; set; }
    public virtual string string_to_hash { get; set; }
    public virtual long[] invoice_line_ids { get; set; }
    public virtual string invoice_date { get; set; }
    public virtual string invoice_date_due { get; set; }
    public virtual string delivery_date { get; set; }
    public virtual bool show_delivery_date { get; set; }
    public virtual object invoice_payment_term_id { get; set; }
    public virtual string needed_terms { get; set; }
    public virtual bool needed_terms_dirty { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object commercial_partner_id { get; set; }
    public virtual object partner_shipping_id { get; set; }
    public virtual object partner_bank_id { get; set; }
    public virtual object fiscal_position_id { get; set; }
    public virtual string payment_reference { get; set; }
    public virtual bool display_qr_code { get; set; }
    public virtual string qr_code_method { get; set; }
    public virtual string invoice_outstanding_credits_debits_widget { get; set; }
    public virtual bool invoice_has_outstanding { get; set; }
    public virtual string invoice_payments_widget { get; set; }
    public virtual object company_currency_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual long direction_sign { get; set; }
    public virtual string amount_untaxed { get; set; }
    public virtual string amount_tax { get; set; }
    public virtual string amount_total { get; set; }
    public virtual string amount_residual { get; set; }
    public virtual string amount_untaxed_signed { get; set; }
    public virtual string amount_tax_signed { get; set; }
    public virtual string amount_total_signed { get; set; }
    public virtual string amount_total_in_currency_signed { get; set; }
    public virtual string amount_residual_signed { get; set; }
    public virtual string tax_totals { get; set; }
    public virtual string payment_state { get; set; }
    public virtual string amount_total_words { get; set; }
    public virtual object reversed_entry_id { get; set; }
    public virtual long[] reversal_move_id { get; set; }
    public virtual object invoice_vendor_bill_id { get; set; }
    public virtual string invoice_source_email { get; set; }
    public virtual string invoice_partner_display_name { get; set; }
    public virtual bool quick_edit_mode { get; set; }
    public virtual string quick_edit_total_amount { get; set; }
    public virtual string quick_encoding_vals { get; set; }
    public virtual string narration { get; set; }
    public virtual bool is_move_sent { get; set; }
    public virtual bool is_being_sent { get; set; }
    public virtual string move_sent_values { get; set; }
    public virtual object invoice_user_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual string invoice_origin { get; set; }
    public virtual object invoice_incoterm_id { get; set; }
    public virtual string incoterm_location { get; set; }
    public virtual object invoice_cash_rounding_id { get; set; }
    public virtual string send_and_print_values { get; set; }
    public virtual object invoice_pdf_report_id { get; set; }
    public virtual string invoice_pdf_report_file { get; set; }
    public virtual string invoice_filter_type_domain { get; set; }
    public virtual object bank_partner_id { get; set; }
    public virtual string tax_lock_date_message { get; set; }
    public virtual bool display_inactive_currency_warning { get; set; }
    public virtual object tax_country_id { get; set; }
    public virtual string tax_country_code { get; set; }
    public virtual bool has_reconciled_entries { get; set; }
    public virtual bool show_reset_to_draft_button { get; set; }
    public virtual string partner_credit_warning { get; set; }
    public virtual string partner_credit { get; set; }
    public virtual long[] duplicated_ref_ids { get; set; }
    public virtual bool need_cancel_request { get; set; }
    public virtual string payment_term_details { get; set; }
    public virtual bool show_payment_term_details { get; set; }
    public virtual bool show_discount_details { get; set; }
    public virtual string abnormal_amount_warning { get; set; }
    public virtual string abnormal_date_warning { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long[] payment_ids { get; set; }
    public virtual long[] statement_line_ids { get; set; }
    public virtual object ubl_cii_xml_id { get; set; }
    public virtual string ubl_cii_xml_file { get; set; }
    public virtual string extract_state { get; set; }
    public virtual string extract_status { get; set; }
    public virtual string extract_error_message { get; set; }
    public virtual string extract_document_uuid { get; set; }
    public virtual bool extract_can_show_send_button { get; set; }
    public virtual bool is_in_extractable_state { get; set; }
    public virtual bool extract_state_processed { get; set; }
    public virtual long[] extract_word_ids { get; set; }
    public virtual object extract_attachment_id { get; set; }
    public virtual bool extract_can_show_banners { get; set; }
    public virtual long extract_detected_layout { get; set; }
    public virtual string extract_partner_name { get; set; }
    public virtual long[] transaction_ids { get; set; }
    public virtual long[] authorized_transaction_ids { get; set; }
    public virtual string amount_paid { get; set; }
    public virtual long[] calendar_booking_ids { get; set; }
    public virtual object team_id { get; set; }
    public virtual long sale_order_count { get; set; }
    public virtual object website_id { get; set; }
}