namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class AccountReconcileModel
{
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual bool active { get; set; }
    public virtual string name { get; set; }
    public virtual long sequence { get; set; }
    public virtual object company_id { get; set; }
    public virtual string rule_type { get; set; }
    public virtual bool auto_reconcile { get; set; }
    public virtual bool to_check { get; set; }
    public virtual string matching_order { get; set; }
    public virtual bool match_text_location_label { get; set; }
    public virtual bool match_text_location_note { get; set; }
    public virtual bool match_text_location_reference { get; set; }
    public virtual long[] match_journal_ids { get; set; }
    public virtual string match_nature { get; set; }
    public virtual string match_amount { get; set; }
    public virtual double match_amount_min { get; set; }
    public virtual double match_amount_max { get; set; }
    public virtual string match_label { get; set; }
    public virtual string match_label_param { get; set; }
    public virtual string match_note { get; set; }
    public virtual string match_note_param { get; set; }
    public virtual string match_transaction_type { get; set; }
    public virtual string match_transaction_type_param { get; set; }
    public virtual bool match_same_currency { get; set; }
    public virtual bool allow_payment_tolerance { get; set; }
    public virtual double payment_tolerance_param { get; set; }
    public virtual string payment_tolerance_type { get; set; }
    public virtual bool match_partner { get; set; }
    public virtual long[] match_partner_ids { get; set; }
    public virtual long[] match_partner_category_ids { get; set; }
    public virtual long[] line_ids { get; set; }
    public virtual long[] partner_mapping_line_ids { get; set; }
    public virtual long past_months_limit { get; set; }
    public virtual string decimal_separator { get; set; }
    public virtual bool show_decimal_separator { get; set; }
    public virtual long number_entries { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}