namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class AppointmentType
{
    public virtual object website_id { get; set; }
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual long sequence { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual double appointment_duration { get; set; }
    public virtual string appointment_duration_formatted { get; set; }
    public virtual string appointment_tz { get; set; }
    public virtual object location_id { get; set; }
    public virtual string location { get; set; }
    public virtual string event_videocall_source { get; set; }
    public virtual bool allow_guests { get; set; }
    public virtual string start_datetime { get; set; }
    public virtual string end_datetime { get; set; }
    public virtual object booked_mail_template_id { get; set; }
    public virtual object canceled_mail_template_id { get; set; }
    public virtual string assign_method { get; set; }
    public virtual string user_assign_method { get; set; }
    public virtual string avatars_display { get; set; }
    public virtual string category { get; set; }
    public virtual long[] country_ids { get; set; }
    public virtual string message_confirmation { get; set; }
    public virtual string message_intro { get; set; }
    public virtual double min_cancellation_hours { get; set; }
    public virtual double min_schedule_hours { get; set; }
    public virtual long max_schedule_days { get; set; }
    public virtual long[] question_ids { get; set; }
    public virtual long[] reminder_ids { get; set; }
    public virtual string schedule_based_on { get; set; }
    public virtual long[] slot_ids { get; set; }
    public virtual long[] staff_user_ids { get; set; }
    public virtual long staff_user_count { get; set; }
    public virtual long[] resource_ids { get; set; }
    public virtual long resource_count { get; set; }
    public virtual bool resource_manual_confirmation { get; set; }
    public virtual double resource_manual_confirmation_percentage { get; set; }
    public virtual bool resource_manage_capacity { get; set; }
    public virtual long resource_total_capacity { get; set; }
    public virtual long appointment_count { get; set; }
    public virtual long appointment_count_report { get; set; }
    public virtual long[] appointment_invite_ids { get; set; }
    public virtual long appointment_invite_count { get; set; }
    public virtual long[] meeting_ids { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual bool work_hours_activated { get; set; }
    public virtual bool has_payment_step { get; set; }
    public virtual object product_id { get; set; }
}