namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ApprovalRequest
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual object category_id { get; set; }
    public virtual string category_image { get; set; }
    public virtual long[] approver_ids { get; set; }
    public virtual long[] user_ids { get; set; }
    public virtual object company_id { get; set; }
    public virtual string date { get; set; }
    public virtual string date_start { get; set; }
    public virtual string date_end { get; set; }
    public virtual double quantity { get; set; }
    public virtual string location { get; set; }
    public virtual string date_confirmed { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string reference { get; set; }
    public virtual double amount { get; set; }
    public virtual string reason { get; set; }
    public virtual string request_status { get; set; }
    public virtual object request_owner_id { get; set; }
    public virtual string user_status { get; set; }
    public virtual bool has_access_to_request { get; set; }
    public virtual bool change_request_owner { get; set; }
    public virtual long attachment_number { get; set; }
    public virtual long[] product_line_ids { get; set; }
    public virtual string has_date { get; set; }
    public virtual string has_period { get; set; }
    public virtual string has_quantity { get; set; }
    public virtual string has_amount { get; set; }
    public virtual string has_reference { get; set; }
    public virtual string has_partner { get; set; }
    public virtual string has_payment_method { get; set; }
    public virtual string has_location { get; set; }
    public virtual string has_product { get; set; }
    public virtual string requirer_document { get; set; }
    public virtual long approval_minimum { get; set; }
    public virtual string approval_type { get; set; }
    public virtual bool approver_sequence { get; set; }
    public virtual bool automated_sequence { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}