namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class CalendarEvent
{
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual string description { get; set; }
    public virtual object user_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string location { get; set; }
    public virtual string videocall_location { get; set; }
    public virtual string access_token { get; set; }
    public virtual string videocall_source { get; set; }
    public virtual object videocall_channel_id { get; set; }
    public virtual string privacy { get; set; }
    public virtual string show_as { get; set; }
    public virtual bool is_highlighted { get; set; }
    public virtual bool is_organizer_alone { get; set; }
    public virtual bool active { get; set; }
    public virtual long[] categ_ids { get; set; }
    public virtual string start { get; set; }
    public virtual string stop { get; set; }
    public virtual string display_time { get; set; }
    public virtual bool allday { get; set; }
    public virtual string start_date { get; set; }
    public virtual string stop_date { get; set; }
    public virtual double duration { get; set; }
    public virtual string res_id { get; set; }
    public virtual object res_model_id { get; set; }
    public virtual string res_model { get; set; }
    public virtual string res_model_name { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual long[] attendee_ids { get; set; }
    public virtual object current_attendee { get; set; }
    public virtual string current_status { get; set; }
    public virtual bool should_show_status { get; set; }
    public virtual long[] partner_ids { get; set; }
    public virtual long[] invalid_email_partner_ids { get; set; }
    public virtual long[] alarm_ids { get; set; }
    public virtual bool recurrency { get; set; }
    public virtual object recurrence_id { get; set; }
    public virtual bool follow_recurrence { get; set; }
    public virtual string recurrence_update { get; set; }
    public virtual string rrule { get; set; }
    public virtual string rrule_type_ui { get; set; }
    public virtual string rrule_type { get; set; }
    public virtual string event_tz { get; set; }
    public virtual string end_type { get; set; }
    public virtual long interval { get; set; }
    public virtual long count { get; set; }
    public virtual bool mon { get; set; }
    public virtual bool tue { get; set; }
    public virtual bool wed { get; set; }
    public virtual bool thu { get; set; }
    public virtual bool fri { get; set; }
    public virtual bool sat { get; set; }
    public virtual bool sun { get; set; }
    public virtual string month_by { get; set; }
    public virtual long day { get; set; }
    public virtual string weekday { get; set; }
    public virtual string byday { get; set; }
    public virtual string until { get; set; }
    public virtual bool display_description { get; set; }
    public virtual long attendees_count { get; set; }
    public virtual long accepted_count { get; set; }
    public virtual long declined_count { get; set; }
    public virtual long tentative_count { get; set; }
    public virtual long awaiting_count { get; set; }
    public virtual bool user_can_edit { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long[] appointment_answer_input_ids { get; set; }
    public virtual bool appointment_attended { get; set; }
    public virtual object appointment_type_id { get; set; }
    public virtual string appointment_type_schedule_based_on { get; set; }
    public virtual bool appointment_type_manage_capacity { get; set; }
    public virtual object appointment_invite_id { get; set; }
    public virtual long[] appointment_resource_ids { get; set; }
    public virtual long[] resource_ids { get; set; }
    public virtual long[] booking_line_ids { get; set; }
    public virtual long resource_total_capacity_reserved { get; set; }
    public virtual long resource_total_capacity_used { get; set; }
    public virtual string videocall_redirection { get; set; }
    public virtual object appointment_booker_id { get; set; }
    public virtual long[] on_leave_partner_ids { get; set; }
    public virtual long[] on_leave_resource_ids { get; set; }
}