namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class EventEvent
{
    public virtual string cover_properties { get; set; }
    public virtual object website_id { get; set; }
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual string note { get; set; }
    public virtual string description { get; set; }
    public virtual bool active { get; set; }
    public virtual object user_id { get; set; }
    public virtual bool use_barcode { get; set; }
    public virtual object company_id { get; set; }
    public virtual object organizer_id { get; set; }
    public virtual object event_type_id { get; set; }
    public virtual long[] event_mail_ids { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual string registration_properties_definition { get; set; }
    public virtual string kanban_state { get; set; }
    public virtual string kanban_state_label { get; set; }
    public virtual object stage_id { get; set; }
    public virtual string legend_blocked { get; set; }
    public virtual string legend_done { get; set; }
    public virtual string legend_normal { get; set; }
    public virtual long seats_max { get; set; }
    public virtual bool seats_limited { get; set; }
    public virtual long seats_reserved { get; set; }
    public virtual long seats_available { get; set; }
    public virtual long seats_used { get; set; }
    public virtual long seats_taken { get; set; }
    public virtual long[] registration_ids { get; set; }
    public virtual long[] event_ticket_ids { get; set; }
    public virtual bool event_registrations_started { get; set; }
    public virtual bool event_registrations_open { get; set; }
    public virtual bool event_registrations_sold_out { get; set; }
    public virtual string start_sale_datetime { get; set; }
    public virtual string date_tz { get; set; }
    public virtual string date_begin { get; set; }
    public virtual string date_end { get; set; }
    public virtual string date_begin_located { get; set; }
    public virtual string date_end_located { get; set; }
    public virtual bool is_ongoing { get; set; }
    public virtual bool is_one_day { get; set; }
    public virtual bool is_finished { get; set; }
    public virtual object address_id { get; set; }
    public virtual object address_search { get; set; }
    public virtual string address_inline { get; set; }
    public virtual object country_id { get; set; }
    public virtual string lang { get; set; }
    public virtual string badge_format { get; set; }
    public virtual string badge_image { get; set; }
    public virtual string ticket_instructions { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string subtitle { get; set; }
    public virtual bool is_participating { get; set; }
    public virtual bool is_visible_on_website { get; set; }
    public virtual string event_register_url { get; set; }
    public virtual string website_visibility { get; set; }
    public virtual bool website_menu { get; set; }
    public virtual object menu_id { get; set; }
    public virtual bool menu_register_cta { get; set; }
    public virtual bool introduction_menu { get; set; }
    public virtual long[] introduction_menu_ids { get; set; }
    public virtual bool location_menu { get; set; }
    public virtual long[] location_menu_ids { get; set; }
    public virtual string address_name { get; set; }
    public virtual bool register_menu { get; set; }
    public virtual long[] register_menu_ids { get; set; }
    public virtual bool community_menu { get; set; }
    public virtual long[] community_menu_ids { get; set; }
    public virtual bool is_done { get; set; }
    public virtual bool start_today { get; set; }
    public virtual long start_remaining { get; set; }
    public virtual long[] question_ids { get; set; }
    public virtual long[] general_question_ids { get; set; }
    public virtual long[] specific_question_ids { get; set; }
    public virtual bool firebase_enable_push_notifications { get; set; }
}