namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HelpdeskTeam
{
    public virtual long[] rating_ids { get; set; }
    public virtual long rating_percentage_satisfaction { get; set; }
    public virtual long rating_count { get; set; }
    public virtual double rating_avg { get; set; }
    public virtual double rating_avg_percentage { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object alias_id { get; set; }
    public virtual string alias_name { get; set; }
    public virtual object alias_domain_id { get; set; }
    public virtual string alias_domain { get; set; }
    public virtual string alias_defaults { get; set; }
    public virtual string alias_email { get; set; }
    public virtual string name { get; set; }
    public virtual string description { get; set; }
    public virtual bool active { get; set; }
    public virtual object company_id { get; set; }
    public virtual long sequence { get; set; }
    public virtual long color { get; set; }
    public virtual string ticket_properties { get; set; }
    public virtual long[] stage_ids { get; set; }
    public virtual bool auto_assignment { get; set; }
    public virtual string assign_method { get; set; }
    public virtual long[] member_ids { get; set; }
    public virtual string privacy_visibility { get; set; }
    public virtual string privacy_visibility_warning { get; set; }
    public virtual string access_instruction_message { get; set; }
    public virtual long[] ticket_ids { get; set; }
    public virtual bool use_alias { get; set; }
    public virtual bool has_external_mail_server { get; set; }
    public virtual bool allow_portal_ticket_closing { get; set; }
    public virtual bool use_website_helpdesk_form { get; set; }
    public virtual bool use_website_helpdesk_livechat { get; set; }
    public virtual bool use_website_helpdesk_forum { get; set; }
    public virtual bool use_website_helpdesk_slides { get; set; }
    public virtual bool use_website_helpdesk_knowledge { get; set; }
    public virtual bool use_helpdesk_timesheet { get; set; }
    public virtual bool show_knowledge_base { get; set; }
    public virtual bool use_helpdesk_sale_timesheet { get; set; }
    public virtual bool use_credit_notes { get; set; }
    public virtual bool use_coupons { get; set; }
    public virtual bool use_fsm { get; set; }
    public virtual bool use_product_returns { get; set; }
    public virtual bool use_product_repairs { get; set; }
    public virtual bool use_twitter { get; set; }
    public virtual bool use_rating { get; set; }
    public virtual bool portal_show_rating { get; set; }
    public virtual bool use_sla { get; set; }
    public virtual long unassigned_tickets { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual long open_ticket_count { get; set; }
    public virtual long sla_policy_count { get; set; }
    public virtual long ticket_closed { get; set; }
    public virtual double success_rate { get; set; }
    public virtual long urgent_ticket { get; set; }
    public virtual long sla_failed { get; set; }
    public virtual bool auto_close_ticket { get; set; }
    public virtual long auto_close_day { get; set; }
    public virtual long[] from_stage_ids { get; set; }
    public virtual object to_stage_id { get; set; }
    public virtual string alias_email_from { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string alias_full_name { get; set; }
    public virtual object alias_model_id { get; set; }
    public virtual long alias_force_thread_id { get; set; }
    public virtual object alias_parent_model_id { get; set; }
    public virtual long alias_parent_thread_id { get; set; }
    public virtual string alias_contact { get; set; }
    public virtual bool alias_incoming_local { get; set; }
    public virtual string alias_bounced_content { get; set; }
    public virtual string alias_status { get; set; }
}