namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrApplicant
{
    public virtual string duration_tracking { get; set; }
    public virtual object campaign_id { get; set; }
    public virtual object source_id { get; set; }
    public virtual object medium_id { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string phone_sanitized { get; set; }
    public virtual bool phone_sanitized_blacklisted { get; set; }
    public virtual bool phone_blacklisted { get; set; }
    public virtual bool mobile_blacklisted { get; set; }
    public virtual string phone_mobile_search { get; set; }
    public virtual string email_normalized { get; set; }
    public virtual bool is_blacklisted { get; set; }
    public virtual long message_bounce { get; set; }
    public virtual string email_cc { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual string description { get; set; }
    public virtual string email_from { get; set; }
    public virtual double probability { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string create_date { get; set; }
    public virtual object stage_id { get; set; }
    public virtual object last_stage_id { get; set; }
    public virtual long[] categ_ids { get; set; }
    public virtual object company_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual string date_closed { get; set; }
    public virtual string date_open { get; set; }
    public virtual string date_last_stage_update { get; set; }
    public virtual string priority { get; set; }
    public virtual object job_id { get; set; }
    public virtual string salary_proposed_extra { get; set; }
    public virtual string salary_expected_extra { get; set; }
    public virtual double salary_proposed { get; set; }
    public virtual double salary_expected { get; set; }
    public virtual string availability { get; set; }
    public virtual string partner_name { get; set; }
    public virtual string partner_phone { get; set; }
    public virtual string partner_phone_sanitized { get; set; }
    public virtual string partner_mobile { get; set; }
    public virtual string partner_mobile_sanitized { get; set; }
    public virtual object type_id { get; set; }
    public virtual object department_id { get; set; }
    public virtual double day_open { get; set; }
    public virtual double day_close { get; set; }
    public virtual double delay_close { get; set; }
    public virtual long color { get; set; }
    public virtual object emp_id { get; set; }
    public virtual bool emp_is_active { get; set; }
    public virtual string user_email { get; set; }
    public virtual long attachment_number { get; set; }
    public virtual string employee_name { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual string kanban_state { get; set; }
    public virtual string legend_blocked { get; set; }
    public virtual string legend_done { get; set; }
    public virtual string legend_normal { get; set; }
    public virtual long application_count { get; set; }
    public virtual object refuse_reason_id { get; set; }
    public virtual long[] meeting_ids { get; set; }
    public virtual string meeting_display_text { get; set; }
    public virtual string meeting_display_date { get; set; }
    public virtual long[] interviewer_ids { get; set; }
    public virtual string linkedin_profile { get; set; }
    public virtual string application_status { get; set; }
    public virtual object[] applicant_properties { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string extract_state { get; set; }
    public virtual string extract_status { get; set; }
    public virtual string extract_error_message { get; set; }
    public virtual string extract_document_uuid { get; set; }
    public virtual bool extract_can_show_send_button { get; set; }
    public virtual bool is_in_extractable_state { get; set; }
    public virtual bool extract_state_processed { get; set; }
    public virtual long[] applicant_skill_ids { get; set; }
    public virtual long[] skill_ids { get; set; }
    public virtual bool is_interviewer { get; set; }
    public virtual object ref_user_id { get; set; }
    public virtual long[] referral_points_ids { get; set; }
    public virtual long earned_points { get; set; }
    public virtual string referral_state { get; set; }
    public virtual string shared_item_infos { get; set; }
    public virtual long max_points { get; set; }
    public virtual object friend_id { get; set; }
    public virtual object last_valuable_stage_id { get; set; }
    public virtual bool is_accessible_to_current_user { get; set; }
}