namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrAppraisal
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual bool active { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object employee_user_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object department_id { get; set; }
    public virtual string image_128 { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string avatar_128 { get; set; }
    public virtual string avatar_1920 { get; set; }
    public virtual object last_appraisal_id { get; set; }
    public virtual string last_appraisal_date { get; set; }
    public virtual long employee_appraisal_count { get; set; }
    public virtual long uncomplete_goals_count { get; set; }
    public virtual string employee_feedback_template { get; set; }
    public virtual string manager_feedback_template { get; set; }
    public virtual string date_close { get; set; }
    public virtual string state { get; set; }
    public virtual long[] manager_ids { get; set; }
    public virtual long[] manager_user_ids { get; set; }
    public virtual long[] meeting_ids { get; set; }
    public virtual string meeting_count_display { get; set; }
    public virtual string date_final_interview { get; set; }
    public virtual bool is_manager { get; set; }
    public virtual long[] employee_autocomplete_ids { get; set; }
    public virtual bool waiting_feedback { get; set; }
    public virtual string employee_feedback { get; set; }
    public virtual string accessible_employee_feedback { get; set; }
    public virtual bool show_employee_feedback_full { get; set; }
    public virtual string manager_feedback { get; set; }
    public virtual string accessible_manager_feedback { get; set; }
    public virtual bool show_manager_feedback_full { get; set; }
    public virtual bool employee_feedback_published { get; set; }
    public virtual bool manager_feedback_published { get; set; }
    public virtual bool can_see_employee_publish { get; set; }
    public virtual bool can_see_manager_publish { get; set; }
    public virtual object assessment_note { get; set; }
    public virtual string note { get; set; }
    public virtual bool appraisal_plan_posted { get; set; }
    public virtual object[] appraisal_properties { get; set; }
    public virtual object duplicate_appraisal_id { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long[] skill_ids { get; set; }
    public virtual long[] employee_feedback_ids { get; set; }
    public virtual long[] survey_ids { get; set; }
    public virtual long completed_survey_count { get; set; }
    public virtual long total_survey_count { get; set; }
}