namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrEmployee
{
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual string avatar_1920 { get; set; }
    public virtual string avatar_1024 { get; set; }
    public virtual string avatar_512 { get; set; }
    public virtual string avatar_256 { get; set; }
    public virtual string avatar_128 { get; set; }
    public virtual object resource_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual string tz { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual long color { get; set; }
    public virtual object department_id { get; set; }
    public virtual bool member_of_department { get; set; }
    public virtual object job_id { get; set; }
    public virtual string job_title { get; set; }
    public virtual object address_id { get; set; }
    public virtual string work_phone { get; set; }
    public virtual string phone { get; set; }
    public virtual string mobile_phone { get; set; }
    public virtual string work_email { get; set; }
    public virtual string email { get; set; }
    public virtual object work_contact_id { get; set; }
    public virtual object work_location_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual bool share { get; set; }
    public virtual object parent_id { get; set; }
    public virtual object coach_id { get; set; }
    public virtual string hr_presence_state { get; set; }
    public virtual string last_activity { get; set; }
    public virtual string last_activity_time { get; set; }
    public virtual string hr_icon_display { get; set; }
    public virtual bool show_hr_icon_display { get; set; }
    public virtual string im_status { get; set; }
    public virtual bool newly_hired { get; set; }
    public virtual long[] goal_ids { get; set; }
    public virtual long[] badge_ids { get; set; }
    public virtual bool has_badges { get; set; }
    public virtual long[] direct_badge_ids { get; set; }
    public virtual long child_all_count { get; set; }
    public virtual long department_color { get; set; }
    public virtual long child_count { get; set; }
    public virtual bool has_slots { get; set; }
    public virtual object user_partner_id { get; set; }
    public virtual object company_country_id { get; set; }
    public virtual string company_country_code { get; set; }
    public virtual string private_street { get; set; }
    public virtual string private_street2 { get; set; }
    public virtual string private_city { get; set; }
    public virtual object private_state_id { get; set; }
    public virtual string private_zip { get; set; }
    public virtual object private_country_id { get; set; }
    public virtual string private_phone { get; set; }
    public virtual string private_email { get; set; }
    public virtual string lang { get; set; }
    public virtual object country_id { get; set; }
    public virtual string gender { get; set; }
    public virtual string marital { get; set; }
    public virtual string spouse_complete_name { get; set; }
    public virtual string spouse_birthdate { get; set; }
    public virtual long children { get; set; }
    public virtual string place_of_birth { get; set; }
    public virtual object country_of_birth { get; set; }
    public virtual string birthday { get; set; }
    public virtual string ssnid { get; set; }
    public virtual string sinid { get; set; }
    public virtual string identification_id { get; set; }
    public virtual string passport_id { get; set; }
    public virtual object bank_account_id { get; set; }
    public virtual string permit_no { get; set; }
    public virtual string visa_no { get; set; }
    public virtual string visa_expire { get; set; }
    public virtual string work_permit_expiration_date { get; set; }
    public virtual string has_work_permit { get; set; }
    public virtual bool work_permit_scheduled_activity { get; set; }
    public virtual string work_permit_name { get; set; }
    public virtual string additional_note { get; set; }
    public virtual string certificate { get; set; }
    public virtual string study_field { get; set; }
    public virtual string study_school { get; set; }
    public virtual string emergency_contact { get; set; }
    public virtual string emergency_phone { get; set; }
    public virtual long km_home_work { get; set; }
    public virtual string employee_type { get; set; }
    public virtual long[] child_ids { get; set; }
    public virtual long[] category_ids { get; set; }
    public virtual string notes { get; set; }
    public virtual string barcode { get; set; }
    public virtual string pin { get; set; }
    public virtual object departure_reason_id { get; set; }
    public virtual string departure_description { get; set; }
    public virtual string departure_date { get; set; }
    public virtual string id_card { get; set; }
    public virtual string driving_license { get; set; }
    public virtual string private_car_plate { get; set; }
    public virtual object currency_id { get; set; }
    public virtual long related_partners_count { get; set; }
    public virtual object[] employee_properties { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string hourly_cost { get; set; }
    public virtual long[] subordinate_ids { get; set; }
    public virtual bool is_subordinate { get; set; }
    public virtual long[] resume_line_ids { get; set; }
    public virtual long[] employee_skill_ids { get; set; }
    public virtual long[] skill_ids { get; set; }
    public virtual object default_planning_role_id { get; set; }
    public virtual long[] planning_role_ids { get; set; }
    public virtual string employee_token { get; set; }
    public virtual long[] subscribed_courses { get; set; }
    public virtual bool has_subscribed_courses { get; set; }
    public virtual string courses_completion_text { get; set; }
}