namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrExpense
{
    public virtual string analytic_distribution { get; set; }
    public virtual long analytic_precision { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual string date { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object product_id { get; set; }
    public virtual string product_description { get; set; }
    public virtual object product_uom_id { get; set; }
    public virtual object product_uom_category_id { get; set; }
    public virtual bool product_has_cost { get; set; }
    public virtual bool product_has_tax { get; set; }
    public virtual double quantity { get; set; }
    public virtual string description { get; set; }
    public virtual string message_main_attachment_checksum { get; set; }
    public virtual long nb_attachment { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual string state { get; set; }
    public virtual object sheet_id { get; set; }
    public virtual object approved_by { get; set; }
    public virtual string approved_on { get; set; }
    public virtual long[] duplicate_expense_ids { get; set; }
    public virtual string tax_amount_currency { get; set; }
    public virtual string tax_amount { get; set; }
    public virtual string total_amount_currency { get; set; }
    public virtual string untaxed_amount_currency { get; set; }
    public virtual string total_amount { get; set; }
    public virtual double price_unit { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object company_currency_id { get; set; }
    public virtual bool is_multiple_currency { get; set; }
    public virtual double currency_rate { get; set; }
    public virtual string label_currency_rate { get; set; }
    public virtual string payment_mode { get; set; }
    public virtual object vendor_id { get; set; }
    public virtual object account_id { get; set; }
    public virtual long[] tax_ids { get; set; }
    public virtual string accounting_date { get; set; }
    public virtual bool is_editable { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string predicted_category { get; set; }
    public virtual string extract_state { get; set; }
    public virtual string extract_status { get; set; }
    public virtual string extract_error_message { get; set; }
    public virtual string extract_document_uuid { get; set; }
    public virtual bool extract_can_show_send_button { get; set; }
    public virtual bool is_in_extractable_state { get; set; }
    public virtual bool extract_state_processed { get; set; }
    public virtual bool sample { get; set; }
}