namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrExpenseSheet
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual long[] expense_line_ids { get; set; }
    public virtual long nb_expense { get; set; }
    public virtual string state { get; set; }
    public virtual string approval_state { get; set; }
    public virtual string approval_date { get; set; }
    public virtual object company_id { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object department_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual long[] product_ids { get; set; }
    public virtual string total_amount { get; set; }
    public virtual string untaxed_amount { get; set; }
    public virtual string total_tax_amount { get; set; }
    public virtual string amount_residual { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object company_currency_id { get; set; }
    public virtual bool is_multiple_currency { get; set; }
    public virtual string payment_state { get; set; }
    public virtual string payment_mode { get; set; }
    public virtual object employee_journal_id { get; set; }
    public virtual long[] selectable_payment_method_line_ids { get; set; }
    public virtual object payment_method_line_id { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual string accounting_date { get; set; }
    public virtual long[] account_move_ids { get; set; }
    public virtual long nb_account_move { get; set; }
    public virtual object journal_id { get; set; }
    public virtual bool can_reset { get; set; }
    public virtual bool can_approve { get; set; }
    public virtual string cannot_approve_reason { get; set; }
    public virtual bool is_editable { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}