namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class HrLeave
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object message_main_attachment_id { get; set; }
    public virtual string name { get; set; }
    public virtual string private_name { get; set; }
    public virtual string state { get; set; }
    public virtual object user_id { get; set; }
    public virtual object manager_id { get; set; }
    public virtual object holiday_status_id { get; set; }
    public virtual long color { get; set; }
    public virtual string validation_type { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object employee_company_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual bool active_employee { get; set; }
    public virtual bool tz_mismatch { get; set; }
    public virtual string tz { get; set; }
    public virtual object department_id { get; set; }
    public virtual string notes { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual string date_from { get; set; }
    public virtual string date_to { get; set; }
    public virtual double number_of_days { get; set; }
    public virtual double number_of_hours { get; set; }
    public virtual bool last_several_days { get; set; }
    public virtual string duration_display { get; set; }
    public virtual object meeting_id { get; set; }
    public virtual object parent_id { get; set; }
    public virtual long[] linked_request_ids { get; set; }
    public virtual string holiday_type { get; set; }
    public virtual long[] employee_ids { get; set; }
    public virtual bool multi_employee { get; set; }
    public virtual object category_id { get; set; }
    public virtual object mode_company_id { get; set; }
    public virtual object first_approver_id { get; set; }
    public virtual object second_approver_id { get; set; }
    public virtual bool can_reset { get; set; }
    public virtual bool can_approve { get; set; }
    public virtual bool can_cancel { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual long[] supported_attachment_ids { get; set; }
    public virtual long supported_attachment_ids_count { get; set; }
    public virtual long[] all_employee_ids { get; set; }
    public virtual string leave_type_request_unit { get; set; }
    public virtual bool leave_type_support_document { get; set; }
    public virtual string request_date_from { get; set; }
    public virtual string request_date_to { get; set; }
    public virtual string request_hour_from { get; set; }
    public virtual string request_hour_to { get; set; }
    public virtual string request_date_from_period { get; set; }
    public virtual bool request_unit_half { get; set; }
    public virtual bool request_unit_hours { get; set; }
    public virtual bool is_hatched { get; set; }
    public virtual bool is_striked { get; set; }
    public virtual bool has_mandatory_day { get; set; }
    public virtual bool leave_type_increases_duration { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object overtime_id { get; set; }
    public virtual double employee_overtime { get; set; }
    public virtual bool overtime_deductible { get; set; }
}