namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class KnowledgeArticle
{
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual string html_field_history { get; set; }
    public virtual string html_field_history_metadata { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual bool active { get; set; }
    public virtual string name { get; set; }
    public virtual string body { get; set; }
    public virtual string icon { get; set; }
    public virtual object cover_image_id { get; set; }
    public virtual string cover_image_url { get; set; }
    public virtual double cover_image_position { get; set; }
    public virtual bool is_locked { get; set; }
    public virtual bool full_width { get; set; }
    public virtual string article_url { get; set; }
    public virtual string internal_permission { get; set; }
    public virtual string inherited_permission { get; set; }
    public virtual object inherited_permission_parent_id { get; set; }
    public virtual long[] article_member_ids { get; set; }
    public virtual bool user_has_access { get; set; }
    public virtual bool user_has_access_parent_path { get; set; }
    public virtual bool user_has_write_access { get; set; }
    public virtual bool user_can_read { get; set; }
    public virtual bool user_can_write { get; set; }
    public virtual string user_permission { get; set; }
    public virtual object parent_id { get; set; }
    public virtual string parent_path { get; set; }
    public virtual long[] child_ids { get; set; }
    public virtual bool has_item_parent { get; set; }
    public virtual bool has_item_children { get; set; }
    public virtual bool has_article_children { get; set; }
    public virtual bool is_desynchronized { get; set; }
    public virtual long sequence { get; set; }
    public virtual object root_article_id { get; set; }
    public virtual bool is_article_item { get; set; }
    public virtual object stage_id { get; set; }
    public virtual string category { get; set; }
    public virtual object last_edition_uid { get; set; }
    public virtual string last_edition_date { get; set; }
    public virtual bool is_user_favorite { get; set; }
    public virtual long user_favorite_sequence { get; set; }
    public virtual long[] favorite_ids { get; set; }
    public virtual long favorite_count { get; set; }
    public virtual bool is_article_visible_by_everyone { get; set; }
    public virtual bool is_article_visible { get; set; }
    public virtual bool to_delete { get; set; }
    public virtual string deletion_date { get; set; }
    public virtual string article_properties_definition { get; set; }
    public virtual object[] article_properties { get; set; }
    public virtual bool is_template { get; set; }
    public virtual string template_body { get; set; }
    public virtual object template_category_id { get; set; }
    public virtual long template_category_sequence { get; set; }
    public virtual string template_description { get; set; }
    public virtual string template_name { get; set; }
    public virtual string template_preview { get; set; }
    public virtual long template_sequence { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}