namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class LunchSupplier
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string name { get; set; }
    public virtual string email { get; set; }
    public virtual string email_formatted { get; set; }
    public virtual string phone { get; set; }
    public virtual string street { get; set; }
    public virtual string street2 { get; set; }
    public virtual string zip_code { get; set; }
    public virtual string city { get; set; }
    public virtual object state_id { get; set; }
    public virtual object country_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object responsible_id { get; set; }
    public virtual string send_by { get; set; }
    public virtual double automatic_email_time { get; set; }
    public virtual object cron_id { get; set; }
    public virtual bool mon { get; set; }
    public virtual bool tue { get; set; }
    public virtual bool wed { get; set; }
    public virtual bool thu { get; set; }
    public virtual bool fri { get; set; }
    public virtual bool sat { get; set; }
    public virtual bool sun { get; set; }
    public virtual string recurrency_end_date { get; set; }
    public virtual long[] available_location_ids { get; set; }
    public virtual bool available_today { get; set; }
    public virtual bool order_deadline_passed { get; set; }
    public virtual string tz { get; set; }
    public virtual bool active { get; set; }
    public virtual string moment { get; set; }
    public virtual string delivery { get; set; }
    public virtual string topping_label_1 { get; set; }
    public virtual string topping_label_2 { get; set; }
    public virtual string topping_label_3 { get; set; }
    public virtual long[] topping_ids_1 { get; set; }
    public virtual long[] topping_ids_2 { get; set; }
    public virtual long[] topping_ids_3 { get; set; }
    public virtual string topping_quantity_1 { get; set; }
    public virtual string topping_quantity_2 { get; set; }
    public virtual string topping_quantity_3 { get; set; }
    public virtual bool show_order_button { get; set; }
    public virtual bool show_confirm_button { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}