namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class MailingMailing
{
    public virtual string name { get; set; }
    public virtual object source_id { get; set; }
    public virtual string lang { get; set; }
    public virtual string render_model { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual bool active { get; set; }
    public virtual string subject { get; set; }
    public virtual string preview { get; set; }
    public virtual string email_from { get; set; }
    public virtual bool favorite { get; set; }
    public virtual string favorite_date { get; set; }
    public virtual string sent_date { get; set; }
    public virtual string schedule_type { get; set; }
    public virtual string schedule_date { get; set; }
    public virtual string calendar_date { get; set; }
    public virtual string body_arch { get; set; }
    public virtual string body_html { get; set; }
    public virtual bool is_body_empty { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual bool keep_archives { get; set; }
    public virtual object campaign_id { get; set; }
    public virtual object medium_id { get; set; }
    public virtual string state { get; set; }
    public virtual long color { get; set; }
    public virtual object user_id { get; set; }
    public virtual string mailing_type { get; set; }
    public virtual string mailing_type_description { get; set; }
    public virtual string reply_to_mode { get; set; }
    public virtual string reply_to { get; set; }
    public virtual string mailing_model_real { get; set; }
    public virtual object mailing_model_id { get; set; }
    public virtual string mailing_model_name { get; set; }
    public virtual bool mailing_on_mailing_list { get; set; }
    public virtual string mailing_domain { get; set; }
    public virtual bool mail_server_available { get; set; }
    public virtual object mail_server_id { get; set; }
    public virtual long[] contact_list_ids { get; set; }
    public virtual object mailing_filter_id { get; set; }
    public virtual string mailing_filter_domain { get; set; }
    public virtual long mailing_filter_count { get; set; }
    public virtual bool ab_testing_completed { get; set; }
    public virtual string ab_testing_description { get; set; }
    public virtual bool ab_testing_enabled { get; set; }
    public virtual bool ab_testing_is_winner_mailing { get; set; }
    public virtual long ab_testing_mailings_count { get; set; }
    public virtual long ab_testing_pc { get; set; }
    public virtual string ab_testing_schedule_datetime { get; set; }
    public virtual string ab_testing_winner_selection { get; set; }
    public virtual bool is_ab_test_sent { get; set; }
    public virtual bool kpi_mail_required { get; set; }
    public virtual long[] mailing_trace_ids { get; set; }
    public virtual long total { get; set; }
    public virtual long scheduled { get; set; }
    public virtual long expected { get; set; }
    public virtual long canceled { get; set; }
    public virtual long sent { get; set; }
    public virtual long process { get; set; }
    public virtual long pending { get; set; }
    public virtual long delivered { get; set; }
    public virtual long opened { get; set; }
    public virtual long clicked { get; set; }
    public virtual long replied { get; set; }
    public virtual long bounced { get; set; }
    public virtual long failed { get; set; }
    public virtual double received_ratio { get; set; }
    public virtual double opened_ratio { get; set; }
    public virtual double replied_ratio { get; set; }
    public virtual double bounced_ratio { get; set; }
    public virtual double clicks_ratio { get; set; }
    public virtual long link_trackers_count { get; set; }
    public virtual string next_departure { get; set; }
    public virtual bool next_departure_is_past { get; set; }
    public virtual string warning_message { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual bool use_in_marketing_automation { get; set; }
    public virtual long[] marketing_activity_ids { get; set; }
    public virtual string sms_subject { get; set; }
    public virtual string body_plaintext { get; set; }
    public virtual object sms_template_id { get; set; }
    public virtual bool sms_has_insufficient_credit { get; set; }
    public virtual bool sms_has_unregistered_account { get; set; }
    public virtual bool sms_force_send { get; set; }
    public virtual bool sms_allow_unsubscribe { get; set; }
    public virtual string ab_testing_sms_winner_selection { get; set; }
    public virtual long ab_testing_mailings_sms_count { get; set; }
}