namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class MaintenanceRequest
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string email_cc { get; set; }
    public virtual string name { get; set; }
    public virtual object company_id { get; set; }
    public virtual string description { get; set; }
    public virtual string request_date { get; set; }
    public virtual object owner_user_id { get; set; }
    public virtual object category_id { get; set; }
    public virtual object equipment_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual object stage_id { get; set; }
    public virtual string priority { get; set; }
    public virtual long color { get; set; }
    public virtual string close_date { get; set; }
    public virtual string kanban_state { get; set; }
    public virtual bool archive { get; set; }
    public virtual string maintenance_type { get; set; }
    public virtual string schedule_date { get; set; }
    public virtual object maintenance_team_id { get; set; }
    public virtual double duration { get; set; }
    public virtual bool done { get; set; }
    public virtual string instruction_type { get; set; }
    public virtual string instruction_pdf { get; set; }
    public virtual string instruction_google_slide { get; set; }
    public virtual string instruction_text { get; set; }
    public virtual bool recurring_maintenance { get; set; }
    public virtual long repeat_interval { get; set; }
    public virtual string repeat_unit { get; set; }
    public virtual string repeat_type { get; set; }
    public virtual string repeat_until { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object production_id { get; set; }
    public virtual object workorder_id { get; set; }
    public virtual object production_company_id { get; set; }
    public virtual string maintenance_for { get; set; }
    public virtual object workcenter_id { get; set; }
    public virtual bool block_workcenter { get; set; }
    public virtual long recurring_leaves_count { get; set; }
    public virtual long[] leave_ids { get; set; }
}