namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class MaintenanceEquipment
{
    public virtual object company_id { get; set; }
    public virtual string effective_date { get; set; }
    public virtual object maintenance_team_id { get; set; }
    public virtual object technician_user_id { get; set; }
    public virtual long[] maintenance_ids { get; set; }
    public virtual long maintenance_count { get; set; }
    public virtual long maintenance_open_count { get; set; }
    public virtual long expected_mtbf { get; set; }
    public virtual long mtbf { get; set; }
    public virtual long mttr { get; set; }
    public virtual string estimated_next_failure { get; set; }
    public virtual string latest_failure_date { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual object owner_user_id { get; set; }
    public virtual object category_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string partner_ref { get; set; }
    public virtual string location { get; set; }
    public virtual string model { get; set; }
    public virtual string serial_no { get; set; }
    public virtual string assign_date { get; set; }
    public virtual double cost { get; set; }
    public virtual string note { get; set; }
    public virtual string warranty_date { get; set; }
    public virtual long color { get; set; }
    public virtual string scrap_date { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object employee_id { get; set; }
    public virtual object department_id { get; set; }
    public virtual string equipment_assign_to { get; set; }
    public virtual object workcenter_id { get; set; }
}