namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class MrpProduction
{
    public virtual string analytic_distribution { get; set; }
    public virtual long analytic_precision { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual string priority { get; set; }
    public virtual long backorder_sequence { get; set; }
    public virtual string origin { get; set; }
    public virtual object product_id { get; set; }
    public virtual long[] product_variant_attributes { get; set; }
    public virtual object workcenter_id { get; set; }
    public virtual string product_tracking { get; set; }
    public virtual object product_tmpl_id { get; set; }
    public virtual double product_qty { get; set; }
    public virtual object product_uom_id { get; set; }
    public virtual object lot_producing_id { get; set; }
    public virtual double qty_producing { get; set; }
    public virtual object product_uom_category_id { get; set; }
    public virtual double product_uom_qty { get; set; }
    public virtual object picking_type_id { get; set; }
    public virtual bool use_create_components_lots { get; set; }
    public virtual object location_src_id { get; set; }
    public virtual object warehouse_id { get; set; }
    public virtual object location_dest_id { get; set; }
    public virtual object location_final_id { get; set; }
    public virtual string date_deadline { get; set; }
    public virtual string date_start { get; set; }
    public virtual string date_finished { get; set; }
    public virtual double duration_expected { get; set; }
    public virtual double duration { get; set; }
    public virtual object bom_id { get; set; }
    public virtual string state { get; set; }
    public virtual string reservation_state { get; set; }
    public virtual long[] move_raw_ids { get; set; }
    public virtual long[] move_finished_ids { get; set; }
    public virtual long[] move_byproduct_ids { get; set; }
    public virtual long[] finished_move_line_ids { get; set; }
    public virtual long[] workorder_ids { get; set; }
    public virtual long[] move_dest_ids { get; set; }
    public virtual bool unreserve_visible { get; set; }
    public virtual bool reserve_visible { get; set; }
    public virtual object user_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual double qty_produced { get; set; }
    public virtual object procurement_group_id { get; set; }
    public virtual string product_description_variants { get; set; }
    public virtual object orderpoint_id { get; set; }
    public virtual bool propagate_cancel { get; set; }
    public virtual string delay_alert_date { get; set; }
    public virtual string json_popover { get; set; }
    public virtual long[] scrap_ids { get; set; }
    public virtual long scrap_count { get; set; }
    public virtual long[] unbuild_ids { get; set; }
    public virtual long unbuild_count { get; set; }
    public virtual bool is_locked { get; set; }
    public virtual bool is_planned { get; set; }
    public virtual bool show_final_lots { get; set; }
    public virtual object production_location_id { get; set; }
    public virtual long[] picking_ids { get; set; }
    public virtual long delivery_count { get; set; }
    public virtual bool confirm_cancel { get; set; }
    public virtual string consumption { get; set; }
    public virtual long mrp_production_child_count { get; set; }
    public virtual long mrp_production_source_count { get; set; }
    public virtual long mrp_production_backorder_count { get; set; }
    public virtual bool show_lock { get; set; }
    public virtual string components_availability { get; set; }
    public virtual string components_availability_state { get; set; }
    public virtual double production_capacity { get; set; }
    public virtual bool show_lot_ids { get; set; }
    public virtual bool forecasted_issue { get; set; }
    public virtual bool show_allocation { get; set; }
    public virtual bool allow_workorder_dependencies { get; set; }
    public virtual bool show_produce { get; set; }
    public virtual bool show_produce_all { get; set; }
    public virtual bool is_outdated_bom { get; set; }
    public virtual bool is_delayed { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual double extra_cost { get; set; }
    public virtual bool show_valuation { get; set; }
    public virtual long[] analytic_account_ids { get; set; }
    public virtual long[] eco_ids { get; set; }
    public virtual long eco_count { get; set; }
    public virtual object latest_bom_id { get; set; }
    public virtual long[] check_ids { get; set; }
    public virtual long[] employee_ids { get; set; }
    public virtual long maintenance_count { get; set; }
    public virtual long[] request_ids { get; set; }
    public virtual bool quality_check_todo { get; set; }
    public virtual bool quality_check_fail { get; set; }
    public virtual long[] quality_alert_ids { get; set; }
    public virtual long quality_alert_count { get; set; }
    public virtual long sale_order_count { get; set; }
}