namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class MrpWorkorder
{
    public virtual string _barcode_scanned { get; set; }
    public virtual string name { get; set; }
    public virtual string barcode { get; set; }
    public virtual object workcenter_id { get; set; }
    public virtual string working_state { get; set; }
    public virtual object product_id { get; set; }
    public virtual string product_tracking { get; set; }
    public virtual object product_uom_id { get; set; }
    public virtual object production_id { get; set; }
    public virtual string production_availability { get; set; }
    public virtual string production_state { get; set; }
    public virtual object production_bom_id { get; set; }
    public virtual double qty_production { get; set; }
    public virtual object company_id { get; set; }
    public virtual double qty_producing { get; set; }
    public virtual double qty_remaining { get; set; }
    public virtual double qty_produced { get; set; }
    public virtual bool is_produced { get; set; }
    public virtual string state { get; set; }
    public virtual object leave_id { get; set; }
    public virtual string date_start { get; set; }
    public virtual string date_finished { get; set; }
    public virtual double duration_expected { get; set; }
    public virtual double duration { get; set; }
    public virtual double duration_unit { get; set; }
    public virtual long duration_percent { get; set; }
    public virtual double progress { get; set; }
    public virtual object operation_id { get; set; }
    public virtual string worksheet { get; set; }
    public virtual string worksheet_type { get; set; }
    public virtual string worksheet_google_slide { get; set; }
    public virtual string operation_note { get; set; }
    public virtual long[] move_raw_ids { get; set; }
    public virtual long[] move_finished_ids { get; set; }
    public virtual long[] move_line_ids { get; set; }
    public virtual object finished_lot_id { get; set; }
    public virtual long[] time_ids { get; set; }
    public virtual bool is_user_working { get; set; }
    public virtual long[] working_user_ids { get; set; }
    public virtual long[] last_working_user_id { get; set; }
    public virtual double costs_hour { get; set; }
    public virtual long[] scrap_ids { get; set; }
    public virtual long scrap_count { get; set; }
    public virtual string production_date { get; set; }
    public virtual string json_popover { get; set; }
    public virtual bool show_json_popover { get; set; }
    public virtual string consumption { get; set; }
    public virtual double qty_reported_from_previous_wo { get; set; }
    public virtual bool is_planned { get; set; }
    public virtual bool allow_workorder_dependencies { get; set; }
    public virtual long[] blocked_by_workorder_ids { get; set; }
    public virtual long[] needed_by_workorder_ids { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long[] mo_analytic_account_line_ids { get; set; }
    public virtual long[] wc_analytic_account_line_ids { get; set; }
    public virtual long[] quality_point_ids { get; set; }
    public virtual long quality_point_count { get; set; }
    public virtual long[] check_ids { get; set; }
    public virtual long[] finished_product_check_ids { get; set; }
    public virtual bool quality_check_todo { get; set; }
    public virtual bool quality_check_fail { get; set; }
    public virtual long[] quality_alert_ids { get; set; }
    public virtual long quality_alert_count { get; set; }
    public virtual object current_quality_check_id { get; set; }
    public virtual bool allow_producing_quantity_change { get; set; }
    public virtual bool is_last_lot { get; set; }
    public virtual bool is_first_started_wo { get; set; }
    public virtual bool is_last_unfinished_wo { get; set; }
    public virtual object lot_id { get; set; }
    public virtual object move_id { get; set; }
    public virtual object move_line_id { get; set; }
    public virtual string quality_state { get; set; }
    public virtual double qty_done { get; set; }
    public virtual object test_type_id { get; set; }
    public virtual string test_type { get; set; }
    public virtual object user_id { get; set; }
    public virtual long worksheet_page { get; set; }
    public virtual string picture { get; set; }
    public virtual bool additional { get; set; }
    public virtual string product_description_variants { get; set; }
    public virtual object employee_id { get; set; }
    public virtual string employee_name { get; set; }
    public virtual long[] employee_ids { get; set; }
    public virtual long[] employee_assigned_ids { get; set; }
    public virtual long[] connected_employee_ids { get; set; }
    public virtual long[] allowed_employees { get; set; }
    public virtual bool all_employees_allowed { get; set; }
    public virtual long[] employee_analytic_account_line_ids { get; set; }
}