namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class PosConfig
{
    public virtual string access_token { get; set; }
    public virtual string name { get; set; }
    public virtual long[] printer_ids { get; set; }
    public virtual bool is_order_printer { get; set; }
    public virtual bool is_installed_account_accountant { get; set; }
    public virtual object picking_type_id { get; set; }
    public virtual object journal_id { get; set; }
    public virtual object invoice_journal_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual bool iface_cashdrawer { get; set; }
    public virtual bool iface_electronic_scale { get; set; }
    public virtual bool iface_customer_facing_display { get; set; }
    public virtual bool iface_customer_facing_display_via_proxy { get; set; }
    public virtual bool iface_customer_facing_display_local { get; set; }
    public virtual string iface_customer_facing_display_background_image_1920 { get; set; }
    public virtual bool iface_print_via_proxy { get; set; }
    public virtual bool iface_scan_via_proxy { get; set; }
    public virtual bool iface_big_scrollbars { get; set; }
    public virtual bool iface_print_auto { get; set; }
    public virtual bool iface_print_skip_screen { get; set; }
    public virtual string iface_tax_included { get; set; }
    public virtual object iface_start_categ_id { get; set; }
    public virtual long[] iface_available_categ_ids { get; set; }
    public virtual bool restrict_price_control { get; set; }
    public virtual bool is_margins_costs_accessible_to_every_user { get; set; }
    public virtual bool cash_control { get; set; }
    public virtual bool set_maximum_difference { get; set; }
    public virtual string receipt_header { get; set; }
    public virtual string receipt_footer { get; set; }
    public virtual string proxy_ip { get; set; }
    public virtual bool active { get; set; }
    public virtual string uuid { get; set; }
    public virtual object sequence_id { get; set; }
    public virtual object sequence_line_id { get; set; }
    public virtual long[] session_ids { get; set; }
    public virtual object current_session_id { get; set; }
    public virtual string current_session_state { get; set; }
    public virtual long number_of_rescue_session { get; set; }
    public virtual double last_session_closing_cash { get; set; }
    public virtual string last_session_closing_date { get; set; }
    public virtual string pos_session_username { get; set; }
    public virtual string pos_session_state { get; set; }
    public virtual string pos_session_duration { get; set; }
    public virtual object pricelist_id { get; set; }
    public virtual long[] available_pricelist_ids { get; set; }
    public virtual object company_id { get; set; }
    public virtual object group_pos_manager_id { get; set; }
    public virtual object group_pos_user_id { get; set; }
    public virtual bool iface_tipproduct { get; set; }
    public virtual object tip_product_id { get; set; }
    public virtual long[] fiscal_position_ids { get; set; }
    public virtual object default_fiscal_position_id { get; set; }
    public virtual long[] default_bill_ids { get; set; }
    public virtual bool use_pricelist { get; set; }
    public virtual bool tax_regime_selection { get; set; }
    public virtual bool start_category { get; set; }
    public virtual bool limit_categories { get; set; }
    public virtual bool module_pos_restaurant { get; set; }
    public virtual bool module_pos_discount { get; set; }
    public virtual bool module_pos_mercury { get; set; }
    public virtual bool is_posbox { get; set; }
    public virtual bool is_header_or_footer { get; set; }
    public virtual bool module_pos_hr { get; set; }
    public virtual double amount_authorized_diff { get; set; }
    public virtual long[] payment_method_ids { get; set; }
    public virtual bool company_has_template { get; set; }
    public virtual object current_user_id { get; set; }
    public virtual bool other_devices { get; set; }
    public virtual object rounding_method { get; set; }
    public virtual bool cash_rounding { get; set; }
    public virtual bool only_round_cash_method { get; set; }
    public virtual bool has_active_session { get; set; }
    public virtual bool manual_discount { get; set; }
    public virtual bool ship_later { get; set; }
    public virtual object warehouse_id { get; set; }
    public virtual object route_id { get; set; }
    public virtual string picking_policy { get; set; }
    public virtual bool auto_validate_terminal_payment { get; set; }
    public virtual long[] trusted_config_ids { get; set; }
    public virtual bool show_product_images { get; set; }
    public virtual bool show_category_images { get; set; }
    public virtual long[] note_ids { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual bool module_pos_iot { get; set; }
    public virtual string epson_printer_ip { get; set; }
    public virtual long[] basic_employee_ids { get; set; }
    public virtual long[] advanced_employee_ids { get; set; }
    public virtual bool iface_splitbill { get; set; }
    public virtual bool iface_printbill { get; set; }
    public virtual long[] floor_ids { get; set; }
    public virtual bool set_tip_after_payment { get; set; }
    public virtual bool module_pos_restaurant_appointment { get; set; }
    public virtual bool takeaway { get; set; }
    public virtual object takeaway_fp_id { get; set; }
    public virtual object crm_team_id { get; set; }
    public virtual object down_payment_product_id { get; set; }
    public virtual string status { get; set; }
    public virtual string self_ordering_url { get; set; }
    public virtual bool self_ordering_takeaway { get; set; }
    public virtual string self_ordering_mode { get; set; }
    public virtual string self_ordering_service_mode { get; set; }
    public virtual object self_ordering_default_language_id { get; set; }
    public virtual long[] self_ordering_available_language_ids { get; set; }
    public virtual long[] self_ordering_image_home_ids { get; set; }
    public virtual object self_ordering_default_user_id { get; set; }
    public virtual string self_ordering_pay_after { get; set; }
    public virtual string self_ordering_image_brand { get; set; }
    public virtual string self_ordering_image_brand_name { get; set; }
    public virtual object self_order_online_payment_method_id { get; set; }
}