namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class PosSession
{
    public virtual string access_token { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object company_id { get; set; }
    public virtual object config_id { get; set; }
    public virtual string name { get; set; }
    public virtual object user_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual string start_at { get; set; }
    public virtual string stop_at { get; set; }
    public virtual string state { get; set; }
    public virtual long sequence_number { get; set; }
    public virtual long login_number { get; set; }
    public virtual string opening_notes { get; set; }
    public virtual string closing_notes { get; set; }
    public virtual bool cash_control { get; set; }
    public virtual object cash_journal_id { get; set; }
    public virtual string cash_register_balance_end_real { get; set; }
    public virtual string cash_register_balance_start { get; set; }
    public virtual string cash_register_total_entry_encoding { get; set; }
    public virtual string cash_register_balance_end { get; set; }
    public virtual string cash_register_difference { get; set; }
    public virtual string cash_real_transaction { get; set; }
    public virtual long[] order_ids { get; set; }
    public virtual long order_count { get; set; }
    public virtual long[] statement_line_ids { get; set; }
    public virtual bool failed_pickings { get; set; }
    public virtual long picking_count { get; set; }
    public virtual long[] picking_ids { get; set; }
    public virtual bool rescue { get; set; }
    public virtual object move_id { get; set; }
    public virtual long[] payment_method_ids { get; set; }
    public virtual double total_payments_amount { get; set; }
    public virtual bool is_in_company_currency { get; set; }
    public virtual bool update_stock_at_closing { get; set; }
    public virtual long[] bank_payment_ids { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object crm_team_id { get; set; }
}