using System.Text.Json.Serialization;

namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ProductProduct
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual double price_extra { get; set; }
    public virtual double lst_price { get; set; }
    public virtual string default_code { get; set; }
    public virtual string code { get; set; }
    public virtual string partner_ref { get; set; }
    public virtual bool active { get; set; }
    public virtual object product_tmpl_id { get; set; }
    public virtual string barcode { get; set; }
    public virtual long[] product_template_attribute_value_ids { get; set; }
    public virtual long[] product_template_variant_value_ids { get; set; }
    public virtual string combination_indices { get; set; }
    public virtual bool is_product_variant { get; set; }
    public virtual double standard_price { get; set; }
    public virtual double volume { get; set; }
    public virtual double weight { get; set; }
    public virtual long pricelist_item_count { get; set; }
    public virtual long[] product_document_ids { get; set; }
    public virtual long product_document_count { get; set; }
    public virtual long[] packaging_ids { get; set; }
    public virtual long[] additional_product_tag_ids { get; set; }
    public virtual long[] all_product_tag_ids { get; set; }
    public virtual string image_variant_1920 { get; set; }
    public virtual string image_variant_1024 { get; set; }
    public virtual string image_variant_512 { get; set; }
    public virtual string image_variant_256 { get; set; }
    public virtual string image_variant_128 { get; set; }
    public virtual bool can_image_variant_1024_be_zoomed { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual bool can_image_1024_be_zoomed { get; set; }
    public virtual string write_date { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string tax_string { get; set; }
    public virtual double sales_count { get; set; }
    public virtual bool product_catalog_product_is_in_sale_order { get; set; }
    public virtual object ribbon_id { get; set; }
    public virtual object website_id { get; set; }
    public virtual long[] product_variant_image_ids { get; set; }
    public virtual double base_unit_count { get; set; }
    public virtual object base_unit_id { get; set; }
    public virtual string base_unit_price { get; set; }
    public virtual string base_unit_name { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual string name { get; set; }
    public virtual long sequence { get; set; }
    public virtual string description { get; set; }
    public virtual string description_purchase { get; set; }
    public virtual string description_sale { get; set; }
    public virtual string detailed_type { get; set; }

    [JsonPropertyName("type")]
    public virtual string type_ { get; set; }

    public virtual object categ_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object cost_currency_id { get; set; }
    public virtual double list_price { get; set; }
    public virtual string volume_uom_name { get; set; }
    public virtual string weight_uom_name { get; set; }
    public virtual bool sale_ok { get; set; }
    public virtual bool purchase_ok { get; set; }
    public virtual object uom_id { get; set; }
    public virtual string uom_name { get; set; }
    public virtual object uom_po_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual long[] seller_ids { get; set; }
    public virtual long[] variant_seller_ids { get; set; }
    public virtual long color { get; set; }
    public virtual long[] attribute_line_ids { get; set; }
    public virtual long[] valid_product_template_attribute_line_ids { get; set; }
    public virtual long[] product_variant_ids { get; set; }
    public virtual object product_variant_id { get; set; }
    public virtual long product_variant_count { get; set; }
    public virtual bool has_configurable_attributes { get; set; }
    public virtual string product_tooltip { get; set; }
    public virtual bool is_favorite { get; set; }
    public virtual long[] product_tag_ids { get; set; }
    public virtual object[] product_properties { get; set; }
    public virtual long[] taxes_id { get; set; }
    public virtual long[] supplier_taxes_id { get; set; }
    public virtual object property_account_income_id { get; set; }
    public virtual object property_account_expense_id { get; set; }
    public virtual long[] account_tag_ids { get; set; }
    public virtual string fiscal_country_codes { get; set; }
    public virtual string service_type { get; set; }
    public virtual string sale_line_warn { get; set; }
    public virtual string sale_line_warn_msg { get; set; }
    public virtual string expense_policy { get; set; }
    public virtual bool visible_expense_policy { get; set; }
    public virtual string invoice_policy { get; set; }
    public virtual long[] optional_product_ids { get; set; }
    public virtual double rating_last_value { get; set; }
    public virtual string rating_last_feedback { get; set; }
    public virtual string rating_last_image { get; set; }
    public virtual long rating_count { get; set; }
    public virtual double rating_avg { get; set; }
    public virtual string rating_avg_text { get; set; }
    public virtual double rating_percentage_satisfaction { get; set; }
    public virtual string rating_last_text { get; set; }
    public virtual string website_description { get; set; }
    public virtual string description_ecommerce { get; set; }
    public virtual long[] alternative_product_ids { get; set; }
    public virtual long[] accessory_product_ids { get; set; }
    public virtual long website_size_x { get; set; }
    public virtual long website_size_y { get; set; }
    public virtual object website_ribbon_id { get; set; }
    public virtual long website_sequence { get; set; }
    public virtual long[] public_categ_ids { get; set; }
    public virtual long[] product_template_image_ids { get; set; }
    public virtual string compare_list_price { get; set; }
}