namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ProjectProject
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual long rating_percentage_satisfaction { get; set; }
    public virtual long rating_count { get; set; }
    public virtual double rating_avg { get; set; }
    public virtual double rating_avg_percentage { get; set; }
    public virtual object alias_id { get; set; }
    public virtual string alias_name { get; set; }
    public virtual object alias_domain_id { get; set; }
    public virtual string alias_domain { get; set; }
    public virtual string alias_defaults { get; set; }
    public virtual string alias_email { get; set; }
    public virtual string access_url { get; set; }
    public virtual string access_token { get; set; }
    public virtual string access_warning { get; set; }
    public virtual string name { get; set; }
    public virtual string description { get; set; }
    public virtual bool active { get; set; }
    public virtual long sequence { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object analytic_account_id { get; set; }
    public virtual string analytic_account_balance { get; set; }
    public virtual long[] favorite_user_ids { get; set; }
    public virtual bool is_favorite { get; set; }
    public virtual string label_tasks { get; set; }
    public virtual long[] tasks { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual long[] type_ids { get; set; }
    public virtual long task_count { get; set; }
    public virtual long open_task_count { get; set; }
    public virtual long[] task_ids { get; set; }
    public virtual long color { get; set; }
    public virtual object user_id { get; set; }
    public virtual string privacy_visibility { get; set; }
    public virtual string privacy_visibility_warning { get; set; }
    public virtual string access_instruction_message { get; set; }
    public virtual string date_start { get; set; }
    public virtual string date { get; set; }
    public virtual bool allow_task_dependencies { get; set; }
    public virtual bool allow_milestones { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual string task_properties_definition { get; set; }
    public virtual long[] collaborator_ids { get; set; }
    public virtual long collaborator_count { get; set; }
    public virtual string rating_request_deadline { get; set; }
    public virtual bool rating_active { get; set; }
    public virtual string rating_status { get; set; }
    public virtual string rating_status_period { get; set; }
    public virtual long[] update_ids { get; set; }
    public virtual object last_update_id { get; set; }
    public virtual string last_update_status { get; set; }
    public virtual long last_update_color { get; set; }
    public virtual long[] milestone_ids { get; set; }
    public virtual bool is_milestone_exceeded { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string alias_full_name { get; set; }
    public virtual object alias_model_id { get; set; }
    public virtual long alias_force_thread_id { get; set; }
    public virtual object alias_parent_model_id { get; set; }
    public virtual long alias_parent_thread_id { get; set; }
    public virtual string alias_contact { get; set; }
    public virtual bool alias_incoming_local { get; set; }
    public virtual string alias_bounced_content { get; set; }
    public virtual string alias_status { get; set; }
}