namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ProjectTask
{
    public virtual string html_field_history { get; set; }
    public virtual string html_field_history_metadata { get; set; }
    public virtual string duration_tracking { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual double rating_last_value { get; set; }
    public virtual string rating_last_feedback { get; set; }
    public virtual string rating_last_image { get; set; }
    public virtual long rating_count { get; set; }
    public virtual double rating_avg { get; set; }
    public virtual string rating_avg_text { get; set; }
    public virtual double rating_percentage_satisfaction { get; set; }
    public virtual string rating_last_text { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual string email_cc { get; set; }
    public virtual string access_url { get; set; }
    public virtual string access_token { get; set; }
    public virtual string access_warning { get; set; }
    public virtual bool active { get; set; }
    public virtual string name { get; set; }
    public virtual string description { get; set; }
    public virtual string priority { get; set; }
    public virtual long sequence { get; set; }
    public virtual object stage_id { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual string state { get; set; }
    public virtual bool is_closed { get; set; }
    public virtual string create_date { get; set; }
    public virtual string write_date { get; set; }
    public virtual string date_end { get; set; }
    public virtual string date_assign { get; set; }
    public virtual string date_deadline { get; set; }
    public virtual string date_last_stage_update { get; set; }
    public virtual object project_id { get; set; }
    public virtual bool display_in_project { get; set; }
    public virtual object[] task_properties { get; set; }
    public virtual double allocated_hours { get; set; }
    public virtual double subtask_allocated_hours { get; set; }
    public virtual long[] user_ids { get; set; }
    public virtual string portal_user_names { get; set; }
    public virtual long[] personal_stage_type_ids { get; set; }
    public virtual object personal_stage_id { get; set; }
    public virtual object personal_stage_type_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual long color { get; set; }
    public virtual bool rating_active { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual object displayed_image_id { get; set; }
    public virtual object parent_id { get; set; }
    public virtual long[] child_ids { get; set; }
    public virtual long subtask_count { get; set; }
    public virtual long closed_subtask_count { get; set; }
    public virtual string project_privacy_visibility { get; set; }
    public virtual double working_hours_open { get; set; }
    public virtual double working_hours_close { get; set; }
    public virtual double working_days_open { get; set; }
    public virtual double working_days_close { get; set; }
    public virtual bool allow_milestones { get; set; }
    public virtual object milestone_id { get; set; }
    public virtual bool has_late_and_unreached_milestone { get; set; }
    public virtual bool allow_task_dependencies { get; set; }
    public virtual long[] depend_on_ids { get; set; }
    public virtual long depend_on_count { get; set; }
    public virtual long[] dependent_ids { get; set; }
    public virtual long dependent_tasks_count { get; set; }
    public virtual bool display_parent_task_button { get; set; }
    public virtual bool current_user_same_company_partner { get; set; }
    public virtual bool recurring_task { get; set; }
    public virtual long recurring_count { get; set; }
    public virtual object recurrence_id { get; set; }
    public virtual long repeat_interval { get; set; }
    public virtual string repeat_unit { get; set; }
    public virtual string repeat_type { get; set; }
    public virtual string repeat_until { get; set; }
    public virtual object analytic_account_id { get; set; }
    public virtual string display_name { get; set; }
    public virtual long id { get; set; }
    public virtual object create_uid { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string planned_date_begin { get; set; }
    public virtual string planned_date_start { get; set; }
    public virtual bool display_warning_dependency_in_gantt { get; set; }
    public virtual string planning_overlap { get; set; }
    public virtual string dependency_warning { get; set; }
    public virtual string user_names { get; set; }
    public virtual long[] user_skill_ids { get; set; }
}