namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class PurchaseOrder
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string access_url { get; set; }
    public virtual string access_token { get; set; }
    public virtual string access_warning { get; set; }
    public virtual string name { get; set; }
    public virtual string priority { get; set; }
    public virtual string origin { get; set; }
    public virtual string partner_ref { get; set; }
    public virtual string date_order { get; set; }
    public virtual string date_approve { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object dest_address_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual string state { get; set; }
    public virtual long[] order_line { get; set; }
    public virtual string notes { get; set; }
    public virtual long invoice_count { get; set; }
    public virtual long[] invoice_ids { get; set; }
    public virtual string invoice_status { get; set; }
    public virtual string date_planned { get; set; }
    public virtual string date_calendar_start { get; set; }
    public virtual string amount_untaxed { get; set; }
    public virtual string tax_totals { get; set; }
    public virtual string amount_tax { get; set; }
    public virtual string amount_total { get; set; }
    public virtual object fiscal_position_id { get; set; }
    public virtual object tax_country_id { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual object payment_term_id { get; set; }
    public virtual object incoterm_id { get; set; }
    public virtual object product_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual string country_code { get; set; }
    public virtual double currency_rate { get; set; }
    public virtual bool mail_reminder_confirmed { get; set; }
    public virtual bool mail_reception_confirmed { get; set; }
    public virtual bool receipt_reminder_email { get; set; }
    public virtual long reminder_date_before_receipt { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string incoterm_location { get; set; }
    public virtual long incoming_picking_count { get; set; }
    public virtual long[] picking_ids { get; set; }
    public virtual object picking_type_id { get; set; }
    public virtual string default_location_dest_id_usage { get; set; }
    public virtual object group_id { get; set; }
    public virtual bool is_shipped { get; set; }
    public virtual string effective_date { get; set; }
    public virtual double on_time_rate { get; set; }
    public virtual string receipt_status { get; set; }
}