namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class QualityCheck
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual object point_id { get; set; }
    public virtual string title { get; set; }
    public virtual string quality_state { get; set; }
    public virtual string control_date { get; set; }
    public virtual object product_id { get; set; }
    public virtual object picking_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object lot_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual object team_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual long[] alert_ids { get; set; }
    public virtual long alert_count { get; set; }
    public virtual string note { get; set; }
    public virtual object test_type_id { get; set; }
    public virtual string test_type { get; set; }
    public virtual string picture { get; set; }
    public virtual string additional_note { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object workorder_id { get; set; }
    public virtual object workcenter_id { get; set; }
    public virtual object production_id { get; set; }
    public virtual string product_tracking { get; set; }
    public virtual object next_check_id { get; set; }
    public virtual object previous_check_id { get; set; }
    public virtual object move_id { get; set; }
    public virtual object move_line_id { get; set; }
    public virtual object component_id { get; set; }
    public virtual object component_uom_id { get; set; }
    public virtual double qty_done { get; set; }
    public virtual object finished_lot_id { get; set; }
    public virtual bool additional { get; set; }
    public virtual string component_tracking { get; set; }
    public virtual double component_remaining_qty { get; set; }
    public virtual double component_qty_to_do { get; set; }
    public virtual bool is_user_working { get; set; }
    public virtual string consumption { get; set; }
    public virtual string working_state { get; set; }
    public virtual bool is_deleted { get; set; }
    public virtual string result { get; set; }
    public virtual double finished_product_sequence { get; set; }
    public virtual string worksheet_document { get; set; }
    public virtual string worksheet_url { get; set; }
    public virtual long worksheet_page { get; set; }
    public virtual string source_document { get; set; }
    public virtual object employee_id { get; set; }
    public virtual string failure_message { get; set; }
    public virtual double measure { get; set; }
    public virtual string measure_success { get; set; }
    public virtual double tolerance_min { get; set; }
    public virtual double tolerance_max { get; set; }
    public virtual string warning_message { get; set; }
    public virtual string norm_unit { get; set; }
    public virtual double qty_to_test { get; set; }
    public virtual double qty_tested { get; set; }
    public virtual string measure_on { get; set; }
    public virtual object failure_location_id { get; set; }
    public virtual string lot_name { get; set; }
    public virtual object lot_line_id { get; set; }
    public virtual double qty_line { get; set; }
    public virtual object uom_id { get; set; }
    public virtual bool show_lot_text { get; set; }
    public virtual bool is_lot_tested_fractionally { get; set; }
    public virtual double testing_percentage_within_lot { get; set; }
    public virtual object operation_id { get; set; }
}