namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class QualityAlert
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string email_cc { get; set; }
    public virtual string name { get; set; }
    public virtual string description { get; set; }
    public virtual object stage_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object reason_id { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual string date_assign { get; set; }
    public virtual string date_close { get; set; }
    public virtual object picking_id { get; set; }
    public virtual string action_corrective { get; set; }
    public virtual string action_preventive { get; set; }
    public virtual object user_id { get; set; }
    public virtual object team_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object check_id { get; set; }
    public virtual object product_tmpl_id { get; set; }
    public virtual object product_id { get; set; }
    public virtual object lot_id { get; set; }
    public virtual string priority { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object workorder_id { get; set; }
    public virtual object workcenter_id { get; set; }
    public virtual object production_id { get; set; }
    public virtual string title { get; set; }
}