namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ResConfigSettings
{
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string web_app_name { get; set; }
    public virtual object company_id { get; set; }
    public virtual bool is_root_company { get; set; }
    public virtual bool user_default_rights { get; set; }
    public virtual bool module_base_import { get; set; }
    public virtual bool module_google_calendar { get; set; }
    public virtual bool module_microsoft_calendar { get; set; }
    public virtual bool module_mail_plugin { get; set; }
    public virtual bool module_auth_oauth { get; set; }
    public virtual bool module_auth_ldap { get; set; }
    public virtual bool module_account_inter_company_rules { get; set; }
    public virtual bool module_voip { get; set; }
    public virtual bool module_web_unsplash { get; set; }
    public virtual bool module_partner_autocomplete { get; set; }
    public virtual bool module_base_geolocalize { get; set; }
    public virtual bool module_google_recaptcha { get; set; }
    public virtual bool module_website_cf_turnstile { get; set; }
    public virtual string report_footer { get; set; }
    public virtual bool group_multi_currency { get; set; }
    public virtual object external_report_layout_id { get; set; }
    public virtual bool show_effect { get; set; }
    public virtual long company_count { get; set; }
    public virtual long active_user_count { get; set; }
    public virtual long language_count { get; set; }
    public virtual string company_name { get; set; }
    public virtual string company_informations { get; set; }
    public virtual string company_country_code { get; set; }
    public virtual string profiling_enabled_until { get; set; }
    public virtual bool module_product_images { get; set; }
    public virtual string recaptcha_public_key { get; set; }
    public virtual string recaptcha_private_key { get; set; }
    public virtual double recaptcha_min_score { get; set; }
    public virtual bool external_email_server_default { get; set; }
    public virtual long fail_counter { get; set; }
    public virtual object alias_domain_id { get; set; }
    public virtual bool module_google_gmail { get; set; }
    public virtual bool module_microsoft_outlook { get; set; }
    public virtual bool restrict_template_rendering { get; set; }
    public virtual bool use_twilio_rtc_servers { get; set; }
    public virtual string twilio_account_sid { get; set; }
    public virtual string twilio_account_token { get; set; }
    public virtual string sfu_server_url { get; set; }
    public virtual string sfu_server_key { get; set; }
    public virtual string email_primary_color { get; set; }
    public virtual string email_secondary_color { get; set; }
    public virtual string tenor_api_key { get; set; }
    public virtual string tenor_content_filter { get; set; }
    public virtual long tenor_gif_limit { get; set; }
    public virtual string google_translate_api_key { get; set; }
    public virtual string map_box_token { get; set; }
    public virtual bool group_analytic_accounting { get; set; }
    public virtual bool auth_signup_reset_password { get; set; }
    public virtual string auth_signup_uninvited { get; set; }
    public virtual object auth_signup_template_user_id { get; set; }
    public virtual string google_gmail_client_identifier { get; set; }
    public virtual string google_gmail_client_secret { get; set; }
    public virtual bool group_uom { get; set; }
    public virtual bool group_product_variant { get; set; }
    public virtual bool module_loyalty { get; set; }
    public virtual bool group_stock_packaging { get; set; }
    public virtual bool group_product_pricelist { get; set; }
    public virtual bool group_sale_pricelist { get; set; }
    public virtual string product_pricelist_setting { get; set; }
    public virtual string product_weight_in_lbs { get; set; }
    public virtual string product_volume_volume_in_cubic_feet { get; set; }
    public virtual string unsplash_access_key { get; set; }
    public virtual string unsplash_app_id { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual bool module_hr_presence { get; set; }
    public virtual bool module_hr_skills { get; set; }
    public virtual bool module_hr_homeworking { get; set; }
    public virtual bool hr_presence_control_login { get; set; }
    public virtual bool hr_presence_control_email { get; set; }
    public virtual bool hr_presence_control_ip { get; set; }
    public virtual bool module_hr_attendance { get; set; }
    public virtual long hr_presence_control_email_amount { get; set; }
    public virtual string hr_presence_control_ip_list { get; set; }
    public virtual bool hr_employee_self_edit { get; set; }
    public virtual bool partner_autocomplete_insufficient_credit { get; set; }
    public virtual bool portal_allow_api_keys { get; set; }
    public virtual string barcodelookup_api_key { get; set; }
    public virtual bool snailmail_color { get; set; }
    public virtual bool snailmail_cover { get; set; }
    public virtual bool snailmail_duplex { get; set; }
    public virtual bool digest_emails { get; set; }
    public virtual object digest_id { get; set; }
    public virtual bool disable_redirect_firebase_dynamic_link { get; set; }
    public virtual bool enable_ocn { get; set; }
    public virtual string sign_terms { get; set; }
    public virtual string sign_terms_html { get; set; }
    public virtual string sign_terms_type { get; set; }
    public virtual bool sign_preview_ready { get; set; }
    public virtual bool use_sign_terms { get; set; }
    public virtual bool group_manage_template_access { get; set; }
    public virtual bool module_sign_itsme { get; set; }
    public virtual bool has_accounting_entries { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object currency_exchange_journal_id { get; set; }
    public virtual object income_currency_exchange_account_id { get; set; }
    public virtual object expense_currency_exchange_account_id { get; set; }
    public virtual bool has_chart_of_accounts { get; set; }
    public virtual string chart_template { get; set; }
    public virtual object sale_tax_id { get; set; }
    public virtual object purchase_tax_id { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual object account_journal_suspense_account_id { get; set; }
    public virtual object account_journal_payment_debit_account_id { get; set; }
    public virtual object account_journal_payment_credit_account_id { get; set; }
    public virtual object transfer_account_id { get; set; }
    public virtual bool module_account_accountant { get; set; }
    public virtual bool group_warning_account { get; set; }
    public virtual bool group_cash_rounding { get; set; }
    public virtual bool group_show_sale_receipts { get; set; }
    public virtual bool group_show_purchase_receipts { get; set; }
    public virtual bool module_account_budget { get; set; }
    public virtual bool module_account_payment { get; set; }
    public virtual bool module_account_reports { get; set; }
    public virtual bool module_account_check_printing { get; set; }
    public virtual bool module_account_batch_payment { get; set; }
    public virtual bool module_account_sepa { get; set; }
    public virtual bool module_account_sepa_direct_debit { get; set; }
    public virtual bool module_account_bank_statement_import_qif { get; set; }
    public virtual bool module_account_bank_statement_import_ofx { get; set; }
    public virtual bool module_account_bank_statement_import_csv { get; set; }
    public virtual bool module_account_bank_statement_import_camt { get; set; }
    public virtual bool module_currency_rate_live { get; set; }
    public virtual bool module_account_intrastat { get; set; }
    public virtual bool module_product_margin { get; set; }
    public virtual bool module_l10n_eu_oss { get; set; }
    public virtual bool module_account_invoice_extract { get; set; }
    public virtual bool module_snailmail_account { get; set; }
    public virtual bool module_account_peppol { get; set; }
    public virtual bool tax_exigibility { get; set; }
    public virtual object tax_cash_basis_journal_id { get; set; }
    public virtual object account_cash_basis_base_account_id { get; set; }
    public virtual object account_fiscal_country_id { get; set; }
    public virtual bool qr_code { get; set; }
    public virtual bool invoice_is_download { get; set; }
    public virtual bool invoice_is_email { get; set; }
    public virtual object incoterm_id { get; set; }
    public virtual string invoice_terms { get; set; }
    public virtual string invoice_terms_html { get; set; }
    public virtual string terms_type { get; set; }
    public virtual bool display_invoice_amount_total_words { get; set; }
    public virtual bool preview_ready { get; set; }
    public virtual bool use_invoice_terms { get; set; }
    public virtual bool account_use_credit_limit { get; set; }
    public virtual string account_default_credit_limit { get; set; }
    public virtual string country_code { get; set; }
    public virtual bool account_storno { get; set; }
    public virtual bool group_sale_delivery_address { get; set; }
    public virtual string quick_edit_mode { get; set; }
    public virtual object account_journal_early_pay_discount_loss_account_id { get; set; }
    public virtual object account_journal_early_pay_discount_gain_account_id { get; set; }
    public virtual object account_discount_income_allocation_id { get; set; }
    public virtual object account_discount_expense_allocation_id { get; set; }
    public virtual bool is_account_peppol_eligible { get; set; }
    public virtual bool module_project_forecast { get; set; }
    public virtual long planning_generation_interval { get; set; }
    public virtual string planning_employee_unavailabilities { get; set; }
    public virtual long planning_self_unassign_days_before { get; set; }
    public virtual bool module_hr_timesheet { get; set; }
    public virtual bool group_project_rating { get; set; }
    public virtual bool group_project_stages { get; set; }
    public virtual bool group_project_recurring_tasks { get; set; }
    public virtual bool group_project_task_dependencies { get; set; }
    public virtual bool group_project_milestone { get; set; }
    public virtual object analytic_plan_id { get; set; }
    public virtual object website_id { get; set; }
    public virtual string website_name { get; set; }
    public virtual string website_domain { get; set; }
    public virtual string website_homepage_url { get; set; }
    public virtual object website_company_id { get; set; }
    public virtual string website_logo { get; set; }
    public virtual long[] language_ids { get; set; }
    public virtual long website_language_count { get; set; }
    public virtual object website_default_lang_id { get; set; }
    public virtual string website_default_lang_code { get; set; }
    public virtual bool shared_user_account { get; set; }
    public virtual bool website_cookies_bar { get; set; }
    public virtual string google_analytics_key { get; set; }
    public virtual string google_search_console { get; set; }
    public virtual string plausible_shared_key { get; set; }
    public virtual string plausible_site { get; set; }
    public virtual bool cdn_activated { get; set; }
    public virtual string cdn_url { get; set; }
    public virtual string cdn_filters { get; set; }
    public virtual string favicon { get; set; }
    public virtual string social_default_image { get; set; }
    public virtual bool group_multi_website { get; set; }
    public virtual bool has_google_analytics { get; set; }
    public virtual bool has_google_search_console { get; set; }
    public virtual bool has_default_share_image { get; set; }
    public virtual bool has_plausible_shared_key { get; set; }
    public virtual bool module_website_livechat { get; set; }
    public virtual bool module_marketing_automation { get; set; }
    public virtual bool invoice_is_ubl_cii { get; set; }
    public virtual string extract_in_invoice_digitalization_mode { get; set; }
    public virtual string extract_out_invoice_digitalization_mode { get; set; }
    public virtual bool extract_single_line_per_tax { get; set; }
    public virtual bool pay_invoices_online { get; set; }
    public virtual string currency_interval_unit { get; set; }
    public virtual string currency_provider { get; set; }
    public virtual string currency_next_execution_date { get; set; }
    public virtual bool invoice_is_snailmail { get; set; }
    public virtual object channel_id { get; set; }
    public virtual string default_invoice_policy { get; set; }
    public virtual bool group_auto_done_setting { get; set; }
    public virtual bool group_discount_per_so_line { get; set; }
    public virtual bool group_proforma_sales { get; set; }
    public virtual bool group_warning_sale { get; set; }
    public virtual bool automatic_invoice { get; set; }
    public virtual object invoice_mail_template_id { get; set; }
    public virtual long quotation_validity_days { get; set; }
    public virtual bool portal_confirmation_sign { get; set; }
    public virtual bool portal_confirmation_pay { get; set; }
    public virtual double prepayment_percent { get; set; }
    public virtual bool module_delivery { get; set; }
    public virtual bool module_delivery_bpost { get; set; }
    public virtual bool module_delivery_dhl { get; set; }
    public virtual bool module_delivery_easypost { get; set; }
    public virtual bool module_delivery_fedex { get; set; }
    public virtual bool module_delivery_sendcloud { get; set; }
    public virtual bool module_delivery_shiprocket { get; set; }
    public virtual bool module_delivery_ups { get; set; }
    public virtual bool module_delivery_usps { get; set; }
    public virtual bool module_delivery_starshipit { get; set; }
    public virtual bool module_product_email_template { get; set; }
    public virtual bool module_sale_amazon { get; set; }
    public virtual bool module_sale_loyalty { get; set; }
    public virtual bool module_sale_margin { get; set; }
    public virtual bool module_sale_product_matrix { get; set; }
    public virtual bool module_sale_pdf_quote_builder { get; set; }
    public virtual string providers_state { get; set; }
    public virtual string first_provider_label { get; set; }
    public virtual bool is_stripe_supported_country { get; set; }
    public virtual string website_slide_google_app_key { get; set; }
    public virtual bool module_website_sale_slides { get; set; }
    public virtual bool module_website_slides_forum { get; set; }
    public virtual bool module_website_slides_survey { get; set; }
    public virtual bool module_mass_mailing_slides { get; set; }
    public virtual bool group_delivery_invoice_address { get; set; }
    public virtual bool group_show_uom_price { get; set; }
    public virtual bool group_product_price_comparison { get; set; }
    public virtual bool module_account { get; set; }
    public virtual bool module_delivery_mondialrelay { get; set; }
    public virtual bool module_website_sale_autocomplete { get; set; }
    public virtual bool module_website_sale_comparison { get; set; }
    public virtual bool module_website_sale_picking { get; set; }
    public virtual bool module_website_sale_wishlist { get; set; }
    public virtual string add_to_cart_action { get; set; }
    public virtual object cart_recovery_mail_template { get; set; }
    public virtual double cart_abandoned_delay { get; set; }
    public virtual bool send_abandoned_cart_email { get; set; }
    public virtual object salesperson_id { get; set; }
    public virtual object salesteam_id { get; set; }
    public virtual bool website_sale_prevent_zero_price_sale { get; set; }
    public virtual string website_sale_contact_us_button_url { get; set; }
    public virtual bool website_sale_enabled_portal_reorder_button { get; set; }
    public virtual string show_line_subtotals_tax_selection { get; set; }
    public virtual string account_on_checkout { get; set; }
    public virtual bool enabled_extra_checkout_step { get; set; }
    public virtual bool enabled_buy_now_button { get; set; }
}