namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ResCompany
{
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual long sequence { get; set; }
    public virtual object parent_id { get; set; }
    public virtual long[] child_ids { get; set; }
    public virtual long[] all_child_ids { get; set; }
    public virtual string parent_path { get; set; }
    public virtual long[] parent_ids { get; set; }
    public virtual object root_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string report_header { get; set; }
    public virtual string report_footer { get; set; }
    public virtual string company_details { get; set; }
    public virtual bool is_company_details_empty { get; set; }
    public virtual string logo { get; set; }
    public virtual string logo_web { get; set; }
    public virtual bool uses_default_logo { get; set; }
    public virtual object currency_id { get; set; }
    public virtual long[] user_ids { get; set; }
    public virtual string street { get; set; }
    public virtual string street2 { get; set; }
    public virtual string zip { get; set; }
    public virtual string city { get; set; }
    public virtual object state_id { get; set; }
    public virtual long[] bank_ids { get; set; }
    public virtual object country_id { get; set; }
    public virtual string country_code { get; set; }
    public virtual string email { get; set; }
    public virtual string phone { get; set; }
    public virtual string mobile { get; set; }
    public virtual string website { get; set; }
    public virtual string vat { get; set; }
    public virtual string company_registry { get; set; }
    public virtual object paperformat_id { get; set; }
    public virtual object external_report_layout_id { get; set; }
    public virtual string font { get; set; }
    public virtual string primary_color { get; set; }
    public virtual string secondary_color { get; set; }
    public virtual long color { get; set; }
    public virtual string layout_background { get; set; }
    public virtual string layout_background_image { get; set; }
    public virtual long[] uninstalled_l10n_module_ids { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string social_twitter { get; set; }
    public virtual string social_facebook { get; set; }
    public virtual string social_github { get; set; }
    public virtual string social_linkedin { get; set; }
    public virtual string social_youtube { get; set; }
    public virtual string social_instagram { get; set; }
    public virtual string social_tiktok { get; set; }
    public virtual long[] resource_calendar_ids { get; set; }
    public virtual object resource_calendar_id { get; set; }
    public virtual object alias_domain_id { get; set; }
    public virtual string alias_domain_name { get; set; }
    public virtual string bounce_email { get; set; }
    public virtual string bounce_formatted { get; set; }
    public virtual string catchall_email { get; set; }
    public virtual string catchall_formatted { get; set; }
    public virtual string default_from_email { get; set; }
    public virtual string email_formatted { get; set; }
    public virtual string email_primary_color { get; set; }
    public virtual string email_secondary_color { get; set; }
    public virtual long hr_presence_control_email_amount { get; set; }
    public virtual string hr_presence_control_ip_list { get; set; }
    public virtual string employee_properties_definition { get; set; }
    public virtual long partner_gid { get; set; }
    public virtual bool iap_enrich_auto_done { get; set; }
    public virtual bool snailmail_color { get; set; }
    public virtual bool snailmail_cover { get; set; }
    public virtual bool snailmail_duplex { get; set; }
    public virtual string payment_onboarding_payment_method { get; set; }
    public virtual string sign_terms { get; set; }
    public virtual string sign_terms_type { get; set; }
    public virtual string sign_terms_html { get; set; }
    public virtual long fiscalyear_last_day { get; set; }
    public virtual string fiscalyear_last_month { get; set; }
    public virtual string period_lock_date { get; set; }
    public virtual string fiscalyear_lock_date { get; set; }
    public virtual string tax_lock_date { get; set; }
    public virtual string max_tax_lock_date { get; set; }
    public virtual object transfer_account_id { get; set; }
    public virtual bool expects_chart_of_accounts { get; set; }
    public virtual string chart_template { get; set; }
    public virtual string bank_account_code_prefix { get; set; }
    public virtual string cash_account_code_prefix { get; set; }
    public virtual object default_cash_difference_income_account_id { get; set; }
    public virtual object default_cash_difference_expense_account_id { get; set; }
    public virtual object account_journal_suspense_account_id { get; set; }
    public virtual object account_journal_payment_debit_account_id { get; set; }
    public virtual object account_journal_payment_credit_account_id { get; set; }
    public virtual object account_journal_early_pay_discount_gain_account_id { get; set; }
    public virtual object account_journal_early_pay_discount_loss_account_id { get; set; }
    public virtual string transfer_account_code_prefix { get; set; }
    public virtual object account_sale_tax_id { get; set; }
    public virtual object account_purchase_tax_id { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual object currency_exchange_journal_id { get; set; }
    public virtual object income_currency_exchange_account_id { get; set; }
    public virtual object expense_currency_exchange_account_id { get; set; }
    public virtual bool anglo_saxon_accounting { get; set; }
    public virtual long[] bank_journal_ids { get; set; }
    public virtual object incoterm_id { get; set; }
    public virtual bool qr_code { get; set; }
    public virtual bool invoice_is_email { get; set; }
    public virtual bool invoice_is_download { get; set; }
    public virtual bool display_invoice_amount_total_words { get; set; }
    public virtual bool account_use_credit_limit { get; set; }
    public virtual object account_opening_move_id { get; set; }
    public virtual object account_opening_journal_id { get; set; }
    public virtual string account_opening_date { get; set; }
    public virtual string invoice_terms { get; set; }
    public virtual string terms_type { get; set; }
    public virtual string invoice_terms_html { get; set; }
    public virtual object account_default_pos_receivable_account_id { get; set; }
    public virtual object expense_accrual_account_id { get; set; }
    public virtual object revenue_accrual_account_id { get; set; }
    public virtual object automatic_entry_default_journal_id { get; set; }
    public virtual object account_fiscal_country_id { get; set; }
    public virtual long[] account_enabled_tax_country_ids { get; set; }
    public virtual bool tax_exigibility { get; set; }
    public virtual object tax_cash_basis_journal_id { get; set; }
    public virtual object account_cash_basis_base_account_id { get; set; }
    public virtual bool account_storno { get; set; }
    public virtual long[] fiscal_position_ids { get; set; }
    public virtual long[] multi_vat_foreign_country_ids { get; set; }
    public virtual string quick_edit_mode { get; set; }
    public virtual object account_discount_income_allocation_id { get; set; }
    public virtual object account_discount_expense_allocation_id { get; set; }
    public virtual long planning_generation_interval { get; set; }
    public virtual string planning_employee_unavailabilities { get; set; }
    public virtual long planning_self_unassign_days_before { get; set; }
    public virtual object website_id { get; set; }
    public virtual bool invoice_is_ubl_cii { get; set; }
    public virtual string extract_in_invoice_digitalization_mode { get; set; }
    public virtual string extract_out_invoice_digitalization_mode { get; set; }
    public virtual bool extract_single_line_per_tax { get; set; }
    public virtual string currency_interval_unit { get; set; }
    public virtual string currency_next_execution_date { get; set; }
    public virtual string currency_provider { get; set; }
    public virtual bool invoice_is_snailmail { get; set; }
    public virtual bool portal_confirmation_sign { get; set; }
    public virtual bool portal_confirmation_pay { get; set; }
    public virtual double prepayment_percent { get; set; }
    public virtual long quotation_validity_days { get; set; }
    public virtual object sale_discount_product_id { get; set; }
    public virtual string sale_onboarding_payment_method { get; set; }
}