using System.Text.Json.Serialization;

namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class ResPartner
{
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual object website_id { get; set; }
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string email_normalized { get; set; }
    public virtual bool is_blacklisted { get; set; }
    public virtual long message_bounce { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual string avatar_1920 { get; set; }
    public virtual string avatar_1024 { get; set; }
    public virtual string avatar_512 { get; set; }
    public virtual string avatar_256 { get; set; }
    public virtual string avatar_128 { get; set; }
    public virtual string name { get; set; }
    public virtual string complete_name { get; set; }
    public virtual object title { get; set; }
    public virtual object parent_id { get; set; }
    public virtual string parent_name { get; set; }
    public virtual long[] child_ids { get; set; }

    [JsonPropertyName("ref")]
    public virtual string ref_ { get; set; }

    public virtual string lang { get; set; }
    public virtual long active_lang_count { get; set; }
    public virtual string tz { get; set; }
    public virtual string tz_offset { get; set; }
    public virtual object user_id { get; set; }
    public virtual string vat { get; set; }
    public virtual object same_vat_partner_id { get; set; }
    public virtual object same_company_registry_partner_id { get; set; }
    public virtual string company_registry { get; set; }
    public virtual long[] bank_ids { get; set; }
    public virtual string website { get; set; }
    public virtual string comment { get; set; }
    public virtual long[] category_id { get; set; }
    public virtual bool active { get; set; }
    public virtual bool employee { get; set; }
    public virtual string function { get; set; }

    [JsonPropertyName("type")]
    public virtual string type_ { get; set; }

    public virtual string street { get; set; }
    public virtual string street2 { get; set; }
    public virtual string zip { get; set; }
    public virtual string city { get; set; }
    public virtual object state_id { get; set; }
    public virtual object country_id { get; set; }
    public virtual string country_code { get; set; }
    public virtual double partner_latitude { get; set; }
    public virtual double partner_longitude { get; set; }
    public virtual string email { get; set; }
    public virtual string email_formatted { get; set; }
    public virtual string phone { get; set; }
    public virtual string mobile { get; set; }
    public virtual bool is_company { get; set; }
    public virtual bool is_public { get; set; }
    public virtual object industry_id { get; set; }
    public virtual string company_type { get; set; }
    public virtual object company_id { get; set; }
    public virtual long color { get; set; }
    public virtual long[] user_ids { get; set; }
    public virtual bool partner_share { get; set; }
    public virtual string contact_address { get; set; }
    public virtual object commercial_partner_id { get; set; }
    public virtual string commercial_company_name { get; set; }
    public virtual string company_name { get; set; }
    public virtual string barcode { get; set; }
    public virtual object self { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string im_status { get; set; }
    public virtual long[] channel_ids { get; set; }
    public virtual string contact_address_inline { get; set; }
    public virtual long[] starred_message_ids { get; set; }
    public virtual string contact_address_complete { get; set; }
    public virtual string signup_token { get; set; }
    public virtual string signup_type { get; set; }
    public virtual string signup_expiration { get; set; }
    public virtual bool signup_valid { get; set; }
    public virtual string signup_url { get; set; }
    public virtual long meeting_count { get; set; }
    public virtual long[] meeting_ids { get; set; }
    public virtual string calendar_last_notif_ack { get; set; }
    public virtual object property_product_pricelist { get; set; }
    public virtual object team_id { get; set; }
    public virtual string image_medium { get; set; }
    public virtual long[] employee_ids { get; set; }
    public virtual long employees_count { get; set; }
    public virtual long partner_gid { get; set; }
    public virtual string additional_info { get; set; }
    public virtual string phone_sanitized { get; set; }
    public virtual bool phone_sanitized_blacklisted { get; set; }
    public virtual bool phone_blacklisted { get; set; }
    public virtual bool mobile_blacklisted { get; set; }
    public virtual string phone_mobile_search { get; set; }
    public virtual long certifications_count { get; set; }
    public virtual long certifications_company_count { get; set; }
    public virtual string ocn_token { get; set; }
    public virtual long[] payment_token_ids { get; set; }
    public virtual long payment_token_count { get; set; }
    public virtual long signature_count { get; set; }
    public virtual string fiscal_country_codes { get; set; }
    public virtual string credit { get; set; }
    public virtual string credit_to_invoice { get; set; }
    public virtual double credit_limit { get; set; }
    public virtual bool use_partner_credit_limit { get; set; }
    public virtual bool show_credit_limit { get; set; }
    public virtual double days_sales_outstanding { get; set; }
    public virtual string debit { get; set; }
    public virtual string debit_limit { get; set; }
    public virtual string total_invoiced { get; set; }
    public virtual object currency_id { get; set; }
    public virtual long journal_item_count { get; set; }
    public virtual object property_account_payable_id { get; set; }
    public virtual object property_account_receivable_id { get; set; }
    public virtual object property_account_position_id { get; set; }
    public virtual object property_payment_term_id { get; set; }
    public virtual object property_supplier_payment_term_id { get; set; }
    public virtual long[] ref_company_ids { get; set; }
    public virtual bool has_unreconciled_entries { get; set; }
    public virtual string last_time_entries_checked { get; set; }
    public virtual long[] invoice_ids { get; set; }
    public virtual long[] contract_ids { get; set; }
    public virtual long bank_account_count { get; set; }
    public virtual string trust { get; set; }
    public virtual bool ignore_abnormal_invoice_date { get; set; }
    public virtual bool ignore_abnormal_invoice_amount { get; set; }
    public virtual string invoice_warn { get; set; }
    public virtual string invoice_warn_msg { get; set; }
    public virtual long supplier_rank { get; set; }
    public virtual long customer_rank { get; set; }
    public virtual long duplicated_bank_account_partners_count { get; set; }
    public virtual string user_livechat_username { get; set; }
    public virtual long[] project_ids { get; set; }
    public virtual long[] task_ids { get; set; }
    public virtual long task_count { get; set; }
    public virtual long[] visitor_ids { get; set; }
    public virtual string ubl_cii_format { get; set; }
    public virtual string peppol_endpoint { get; set; }
    public virtual string peppol_eas { get; set; }
    public virtual string website_description { get; set; }
    public virtual string website_short_description { get; set; }
    public virtual long sale_order_count { get; set; }
    public virtual long[] sale_order_ids { get; set; }
    public virtual string sale_warn { get; set; }
    public virtual string sale_warn_msg { get; set; }
    public virtual object property_delivery_carrier_id { get; set; }
    public virtual long[] slide_channel_ids { get; set; }
    public virtual long[] slide_channel_completed_ids { get; set; }
    public virtual long slide_channel_count { get; set; }
    public virtual long slide_channel_company_count { get; set; }
    public virtual object last_website_so_id { get; set; }
}