namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SaleOrder
{
    public virtual object campaign_id { get; set; }
    public virtual object source_id { get; set; }
    public virtual object medium_id { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string access_url { get; set; }
    public virtual string access_token { get; set; }
    public virtual string access_warning { get; set; }
    public virtual string name { get; set; }
    public virtual object company_id { get; set; }
    public virtual object partner_id { get; set; }
    public virtual string state { get; set; }
    public virtual bool locked { get; set; }
    public virtual string client_order_ref { get; set; }
    public virtual string create_date { get; set; }
    public virtual string commitment_date { get; set; }
    public virtual string date_order { get; set; }
    public virtual string origin { get; set; }
    public virtual string reference { get; set; }
    public virtual bool require_signature { get; set; }
    public virtual bool require_payment { get; set; }
    public virtual double prepayment_percent { get; set; }
    public virtual string signature { get; set; }
    public virtual string signed_by { get; set; }
    public virtual string signed_on { get; set; }
    public virtual string validity_date { get; set; }
    public virtual object journal_id { get; set; }
    public virtual string note { get; set; }
    public virtual object partner_invoice_id { get; set; }
    public virtual object partner_shipping_id { get; set; }
    public virtual object fiscal_position_id { get; set; }
    public virtual object payment_term_id { get; set; }
    public virtual object pricelist_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual double currency_rate { get; set; }
    public virtual object user_id { get; set; }
    public virtual object team_id { get; set; }
    public virtual long[] order_line { get; set; }
    public virtual string amount_untaxed { get; set; }
    public virtual string amount_tax { get; set; }
    public virtual string amount_total { get; set; }
    public virtual string amount_to_invoice { get; set; }
    public virtual string amount_invoiced { get; set; }
    public virtual long invoice_count { get; set; }
    public virtual long[] invoice_ids { get; set; }
    public virtual string invoice_status { get; set; }
    public virtual long[] transaction_ids { get; set; }
    public virtual long[] authorized_transaction_ids { get; set; }
    public virtual double amount_paid { get; set; }
    public virtual object analytic_account_id { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual double amount_undiscounted { get; set; }
    public virtual string country_code { get; set; }
    public virtual string expected_date { get; set; }
    public virtual bool is_expired { get; set; }
    public virtual string partner_credit_warning { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual object tax_country_id { get; set; }
    public virtual string tax_totals { get; set; }
    public virtual string terms_type { get; set; }
    public virtual string type_name { get; set; }
    public virtual bool show_update_fpos { get; set; }
    public virtual bool has_active_pricelist { get; set; }
    public virtual bool show_update_pricelist { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object carrier_id { get; set; }
    public virtual string delivery_message { get; set; }
    public virtual bool delivery_rating_success { get; set; }
    public virtual bool delivery_set { get; set; }
    public virtual bool recompute_delivery_price { get; set; }
    public virtual bool is_all_service { get; set; }
    public virtual double shipping_weight { get; set; }
    public virtual object pending_email_template_id { get; set; }
    public virtual object website_id { get; set; }
    public virtual string access_point_address { get; set; }
    public virtual bool cart_recovery_email_sent { get; set; }
    public virtual string shop_warning { get; set; }
    public virtual long[] website_order_line { get; set; }
    public virtual string amount_delivery { get; set; }
    public virtual long cart_quantity { get; set; }
    public virtual bool only_services { get; set; }
    public virtual bool is_abandoned_cart { get; set; }
    public virtual long calendar_event_count { get; set; }
}