namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SaleOrderLine
{
    public virtual string analytic_distribution { get; set; }
    public virtual long analytic_precision { get; set; }
    public virtual object order_id { get; set; }
    public virtual long sequence { get; set; }
    public virtual object company_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual object order_partner_id { get; set; }
    public virtual object salesman_id { get; set; }
    public virtual string state { get; set; }
    public virtual object tax_country_id { get; set; }
    public virtual string display_type { get; set; }
    public virtual bool is_downpayment { get; set; }
    public virtual bool is_expense { get; set; }
    public virtual object product_id { get; set; }
    public virtual object product_template_id { get; set; }
    public virtual object product_uom_category_id { get; set; }
    public virtual long[] product_custom_attribute_value_ids { get; set; }
    public virtual long[] product_no_variant_attribute_value_ids { get; set; }
    public virtual string name { get; set; }
    public virtual double product_uom_qty { get; set; }
    public virtual object product_uom { get; set; }
    public virtual long[] tax_id { get; set; }
    public virtual object pricelist_item_id { get; set; }
    public virtual double price_unit { get; set; }
    public virtual double discount { get; set; }
    public virtual string price_subtotal { get; set; }
    public virtual double price_tax { get; set; }
    public virtual string price_total { get; set; }
    public virtual string price_reduce_taxexcl { get; set; }
    public virtual string price_reduce_taxinc { get; set; }
    public virtual object product_packaging_id { get; set; }
    public virtual double product_packaging_qty { get; set; }
    public virtual double customer_lead { get; set; }
    public virtual string qty_delivered_method { get; set; }
    public virtual double qty_delivered { get; set; }
    public virtual double qty_invoiced { get; set; }
    public virtual double qty_to_invoice { get; set; }
    public virtual long[] analytic_line_ids { get; set; }
    public virtual long[] invoice_lines { get; set; }
    public virtual string invoice_status { get; set; }
    public virtual string untaxed_amount_invoiced { get; set; }
    public virtual string untaxed_amount_to_invoice { get; set; }
    public virtual string product_type { get; set; }
    public virtual bool product_updatable { get; set; }
    public virtual bool product_uom_readonly { get; set; }
    public virtual string tax_calculation_rounding_method { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual bool is_delivery { get; set; }
    public virtual double product_qty { get; set; }
    public virtual bool recompute_delivery_price { get; set; }
    public virtual bool is_configurable_product { get; set; }
    public virtual long[] product_template_attribute_value_ids { get; set; }
    public virtual object linked_line_id { get; set; }
    public virtual long[] option_line_ids { get; set; }
    public virtual string name_short { get; set; }
    public virtual string shop_warning { get; set; }
    public virtual long[] calendar_booking_ids { get; set; }
    public virtual object calendar_event_id { get; set; }
}