namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SignRequest
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual object template_id { get; set; }
    public virtual string subject { get; set; }
    public virtual string reference { get; set; }
    public virtual string access_token { get; set; }
    public virtual string share_link { get; set; }
    public virtual long[] request_item_ids { get; set; }
    public virtual string state { get; set; }
    public virtual string completed_document { get; set; }
    public virtual long nb_wait { get; set; }
    public virtual long nb_closed { get; set; }
    public virtual long nb_total { get; set; }
    public virtual string progress { get; set; }
    public virtual bool start_sign { get; set; }
    public virtual bool integrity { get; set; }
    public virtual bool active { get; set; }
    public virtual long[] favorited_ids { get; set; }
    public virtual long color { get; set; }
    public virtual string request_item_infos { get; set; }
    public virtual string last_action_date { get; set; }
    public virtual string completion_date { get; set; }
    public virtual object communication_company_id { get; set; }
    public virtual long[] sign_log_ids { get; set; }
    public virtual long[] template_tags { get; set; }
    public virtual long[] cc_partner_ids { get; set; }
    public virtual string message { get; set; }
    public virtual string message_cc { get; set; }
    public virtual long[] attachment_ids { get; set; }
    public virtual long[] completed_document_attachment_ids { get; set; }
    public virtual bool need_my_signature { get; set; }
    public virtual string validity { get; set; }
    public virtual bool reminder_enabled { get; set; }
    public virtual long reminder { get; set; }
    public virtual string last_reminder { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
}