namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SlideChannel
{
    public virtual object website_id { get; set; }
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual string cover_properties { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual double rating_last_value { get; set; }
    public virtual string rating_last_feedback { get; set; }
    public virtual string rating_last_image { get; set; }
    public virtual long rating_count { get; set; }
    public virtual double rating_avg { get; set; }
    public virtual string rating_avg_text { get; set; }
    public virtual double rating_percentage_satisfaction { get; set; }
    public virtual string rating_last_text { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual string description { get; set; }
    public virtual string description_short { get; set; }
    public virtual string description_html { get; set; }
    public virtual string channel_type { get; set; }
    public virtual long sequence { get; set; }
    public virtual object user_id { get; set; }
    public virtual long color { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual long[] slide_ids { get; set; }
    public virtual long[] slide_content_ids { get; set; }
    public virtual long[] slide_category_ids { get; set; }
    public virtual string slide_last_update { get; set; }
    public virtual long[] slide_partner_ids { get; set; }
    public virtual string promote_strategy { get; set; }
    public virtual object promoted_slide_id { get; set; }
    public virtual string access_token { get; set; }
    public virtual long nbr_document { get; set; }
    public virtual long nbr_video { get; set; }
    public virtual long nbr_infographic { get; set; }
    public virtual long nbr_article { get; set; }
    public virtual long nbr_quiz { get; set; }
    public virtual long total_slides { get; set; }
    public virtual long total_views { get; set; }
    public virtual long total_votes { get; set; }
    public virtual double total_time { get; set; }
    public virtual double rating_avg_stars { get; set; }
    public virtual bool allow_comment { get; set; }
    public virtual object publish_template_id { get; set; }
    public virtual object share_channel_template_id { get; set; }
    public virtual object share_slide_template_id { get; set; }
    public virtual object completed_template_id { get; set; }
    public virtual string enroll { get; set; }
    public virtual string enroll_msg { get; set; }
    public virtual long[] enroll_group_ids { get; set; }
    public virtual string visibility { get; set; }
    public virtual long[] upload_group_ids { get; set; }
    public virtual string website_default_background_image_url { get; set; }
    public virtual long[] channel_partner_ids { get; set; }
    public virtual long[] channel_partner_all_ids { get; set; }
    public virtual long members_count { get; set; }
    public virtual long members_all_count { get; set; }
    public virtual long members_engaged_count { get; set; }
    public virtual long members_completed_count { get; set; }
    public virtual long members_invited_count { get; set; }
    public virtual long[] partner_ids { get; set; }
    public virtual bool completed { get; set; }
    public virtual long completion { get; set; }
    public virtual bool can_upload { get; set; }
    public virtual bool has_requested_access { get; set; }
    public virtual bool is_member { get; set; }
    public virtual bool is_member_invited { get; set; }
    public virtual bool partner_has_new_content { get; set; }
    public virtual long karma_gen_channel_rank { get; set; }
    public virtual long karma_gen_channel_finish { get; set; }
    public virtual long karma_review { get; set; }
    public virtual long karma_slide_comment { get; set; }
    public virtual long karma_slide_vote { get; set; }
    public virtual bool can_review { get; set; }
    public virtual bool can_comment { get; set; }
    public virtual bool can_vote { get; set; }
    public virtual long[] prerequisite_channel_ids { get; set; }
    public virtual long[] prerequisite_of_channel_ids { get; set; }
    public virtual bool prerequisite_user_has_completed { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long members_certified_count { get; set; }
    public virtual long nbr_certification { get; set; }
}