namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SlideSlide
{
    public virtual bool website_published { get; set; }
    public virtual bool is_published { get; set; }
    public virtual bool can_publish { get; set; }
    public virtual string website_url { get; set; }
    public virtual bool is_seo_optimized { get; set; }
    public virtual string website_meta_title { get; set; }
    public virtual string website_meta_description { get; set; }
    public virtual string website_meta_keywords { get; set; }
    public virtual string website_meta_og_img { get; set; }
    public virtual string seo_name { get; set; }
    public virtual string image_1920 { get; set; }
    public virtual string image_1024 { get; set; }
    public virtual string image_512 { get; set; }
    public virtual string image_256 { get; set; }
    public virtual string image_128 { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual bool active { get; set; }
    public virtual long sequence { get; set; }
    public virtual object user_id { get; set; }
    public virtual string description { get; set; }
    public virtual object channel_id { get; set; }
    public virtual long[] tag_ids { get; set; }
    public virtual bool is_preview { get; set; }
    public virtual bool is_new_slide { get; set; }
    public virtual double completion_time { get; set; }
    public virtual bool is_category { get; set; }
    public virtual object category_id { get; set; }
    public virtual long[] slide_ids { get; set; }
    public virtual long[] partner_ids { get; set; }
    public virtual long[] slide_partner_ids { get; set; }
    public virtual object user_membership_id { get; set; }
    public virtual long user_vote { get; set; }
    public virtual bool user_has_completed { get; set; }
    public virtual bool user_has_completed_category { get; set; }
    public virtual long[] question_ids { get; set; }
    public virtual long questions_count { get; set; }
    public virtual long quiz_first_attempt_reward { get; set; }
    public virtual long quiz_second_attempt_reward { get; set; }
    public virtual long quiz_third_attempt_reward { get; set; }
    public virtual long quiz_fourth_attempt_reward { get; set; }
    public virtual bool can_self_mark_completed { get; set; }
    public virtual bool can_self_mark_uncompleted { get; set; }
    public virtual string slide_category { get; set; }
    public virtual string source_type { get; set; }
    public virtual string url { get; set; }
    public virtual string binary_content { get; set; }
    public virtual long[] slide_resource_ids { get; set; }
    public virtual bool slide_resource_downloadable { get; set; }
    public virtual string google_drive_id { get; set; }
    public virtual string html_content { get; set; }
    public virtual string image_binary_content { get; set; }
    public virtual string image_google_url { get; set; }
    public virtual string slide_icon_class { get; set; }
    public virtual string slide_type { get; set; }
    public virtual string document_google_url { get; set; }
    public virtual string document_binary_content { get; set; }
    public virtual string video_url { get; set; }
    public virtual string video_source_type { get; set; }
    public virtual string youtube_id { get; set; }
    public virtual string vimeo_id { get; set; }
    public virtual object website_id { get; set; }
    public virtual string date_published { get; set; }
    public virtual long likes { get; set; }
    public virtual long dislikes { get; set; }
    public virtual string embed_code { get; set; }
    public virtual string embed_code_external { get; set; }
    public virtual string website_share_url { get; set; }
    public virtual long[] embed_ids { get; set; }
    public virtual long embed_count { get; set; }
    public virtual long slide_views { get; set; }
    public virtual long public_views { get; set; }
    public virtual long total_views { get; set; }
    public virtual long comments_count { get; set; }
    public virtual string channel_type { get; set; }
    public virtual bool channel_allow_comment { get; set; }
    public virtual long nbr_document { get; set; }
    public virtual long nbr_video { get; set; }
    public virtual long nbr_infographic { get; set; }
    public virtual long nbr_article { get; set; }
    public virtual long nbr_quiz { get; set; }
    public virtual long total_slides { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object survey_id { get; set; }
    public virtual long nbr_certification { get; set; }
}