namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SocialPost
{
    public virtual string name { get; set; }
    public virtual object source_id { get; set; }
    public virtual string message { get; set; }
    public virtual long[] image_ids { get; set; }
    public virtual string image_urls { get; set; }
    public virtual long[] account_ids { get; set; }
    public virtual bool has_active_accounts { get; set; }
    public virtual long message_length { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string facebook_preview { get; set; }
    public virtual bool display_facebook_preview { get; set; }
    public virtual object instagram_image_id { get; set; }
    public virtual string instagram_access_token { get; set; }
    public virtual bool display_instagram_preview { get; set; }
    public virtual string instagram_preview { get; set; }
    public virtual bool display_linkedin_preview { get; set; }
    public virtual string linkedin_preview { get; set; }
    public virtual string twitter_preview { get; set; }
    public virtual bool has_twitter_accounts { get; set; }
    public virtual string twitter_post_limit_message { get; set; }
    public virtual bool is_twitter_post_limit_exceed { get; set; }
    public virtual bool display_push_notification_attributes { get; set; }
    public virtual string push_notification_title { get; set; }
    public virtual string push_notification_target_url { get; set; }
    public virtual string push_notification_image { get; set; }
    public virtual bool display_push_notifications_preview { get; set; }
    public virtual string push_notifications_preview { get; set; }
    public virtual bool use_visitor_timezone { get; set; }
    public virtual string visitor_domain { get; set; }
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string state { get; set; }
    public virtual bool has_post_errors { get; set; }
    public virtual long[] account_allowed_ids { get; set; }
    public virtual object company_id { get; set; }
    public virtual long[] media_ids { get; set; }
    public virtual long[] live_post_ids { get; set; }
    public virtual string live_posts_by_media { get; set; }
    public virtual string post_method { get; set; }
    public virtual string scheduled_date { get; set; }
    public virtual string published_date { get; set; }
    public virtual string calendar_date { get; set; }
    public virtual bool is_hatched { get; set; }
    public virtual object utm_campaign_id { get; set; }
    public virtual long stream_posts_count { get; set; }
    public virtual long engagement { get; set; }
    public virtual long click_count { get; set; }
    public virtual string youtube_video { get; set; }
    public virtual string youtube_video_id { get; set; }
    public virtual string youtube_video_category_id { get; set; }
    public virtual string youtube_access_token { get; set; }
    public virtual string youtube_title { get; set; }
    public virtual string youtube_description { get; set; }
    public virtual string youtube_preview { get; set; }
    public virtual long youtube_accounts_count { get; set; }
    public virtual long youtube_accounts_other_count { get; set; }
    public virtual string youtube_video_privacy { get; set; }
    public virtual string youtube_video_url { get; set; }
    public virtual string youtube_thumbnail_url { get; set; }
}