namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class StockPicking
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string name { get; set; }
    public virtual string origin { get; set; }
    public virtual string note { get; set; }
    public virtual object backorder_id { get; set; }
    public virtual long[] backorder_ids { get; set; }
    public virtual object return_id { get; set; }
    public virtual long[] return_ids { get; set; }
    public virtual long return_count { get; set; }
    public virtual string move_type { get; set; }
    public virtual string state { get; set; }
    public virtual object group_id { get; set; }
    public virtual string priority { get; set; }
    public virtual string scheduled_date { get; set; }
    public virtual string date_deadline { get; set; }
    public virtual bool has_deadline_issue { get; set; }
    public virtual string date { get; set; }
    public virtual string date_done { get; set; }
    public virtual string delay_alert_date { get; set; }
    public virtual string json_popover { get; set; }
    public virtual object location_id { get; set; }
    public virtual object location_dest_id { get; set; }
    public virtual long[] move_ids { get; set; }
    public virtual long[] move_ids_without_package { get; set; }
    public virtual bool has_scrap_move { get; set; }
    public virtual object picking_type_id { get; set; }
    public virtual string picking_type_code { get; set; }
    public virtual bool picking_type_entire_packs { get; set; }
    public virtual bool use_create_lots { get; set; }
    public virtual bool use_existing_lots { get; set; }
    public virtual bool hide_picking_type { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object company_id { get; set; }
    public virtual object user_id { get; set; }
    public virtual long[] move_line_ids { get; set; }
    public virtual long[] move_line_ids_without_package { get; set; }
    public virtual bool move_line_exist { get; set; }
    public virtual bool has_packages { get; set; }
    public virtual bool show_check_availability { get; set; }
    public virtual bool show_allocation { get; set; }
    public virtual object owner_id { get; set; }
    public virtual bool printed { get; set; }
    public virtual string signature { get; set; }
    public virtual bool is_signed { get; set; }
    public virtual bool is_locked { get; set; }
    public virtual object product_id { get; set; }
    public virtual object lot_id { get; set; }
    public virtual bool show_operations { get; set; }
    public virtual bool show_lots_text { get; set; }
    public virtual bool has_tracking { get; set; }
    public virtual long[] package_level_ids { get; set; }
    public virtual long[] package_level_ids_details { get; set; }
    public virtual string products_availability { get; set; }
    public virtual string products_availability_state { get; set; }
    public virtual object[] picking_properties { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual string country_code { get; set; }
    public virtual object pos_session_id { get; set; }
    public virtual object pos_order_id { get; set; }
    public virtual object sale_id { get; set; }
}