namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class StockMove
{
    public virtual string name { get; set; }
    public virtual long sequence { get; set; }
    public virtual string priority { get; set; }
    public virtual string date { get; set; }
    public virtual string date_deadline { get; set; }
    public virtual object company_id { get; set; }
    public virtual object product_id { get; set; }
    public virtual string description_picking { get; set; }
    public virtual double product_qty { get; set; }
    public virtual double product_uom_qty { get; set; }
    public virtual object product_uom { get; set; }
    public virtual object product_uom_category_id { get; set; }
    public virtual object product_tmpl_id { get; set; }
    public virtual object location_id { get; set; }
    public virtual object location_dest_id { get; set; }
    public virtual object location_final_id { get; set; }
    public virtual string location_usage { get; set; }
    public virtual string location_dest_usage { get; set; }
    public virtual object partner_id { get; set; }
    public virtual long[] move_dest_ids { get; set; }
    public virtual long[] move_orig_ids { get; set; }
    public virtual object picking_id { get; set; }
    public virtual string state { get; set; }
    public virtual bool picked { get; set; }
    public virtual double price_unit { get; set; }
    public virtual string origin { get; set; }
    public virtual string procure_method { get; set; }
    public virtual bool scrapped { get; set; }
    public virtual object scrap_id { get; set; }
    public virtual object group_id { get; set; }
    public virtual object rule_id { get; set; }
    public virtual bool propagate_cancel { get; set; }
    public virtual string delay_alert_date { get; set; }
    public virtual object picking_type_id { get; set; }
    public virtual bool is_inventory { get; set; }
    public virtual long[] move_line_ids { get; set; }
    public virtual object origin_returned_move_id { get; set; }
    public virtual long[] returned_move_ids { get; set; }
    public virtual double availability { get; set; }
    public virtual object restrict_partner_id { get; set; }
    public virtual long[] route_ids { get; set; }
    public virtual object warehouse_id { get; set; }
    public virtual string has_tracking { get; set; }
    public virtual double quantity { get; set; }
    public virtual bool show_operations { get; set; }
    public virtual string picking_code { get; set; }
    public virtual bool show_details_visible { get; set; }
    public virtual string product_type { get; set; }
    public virtual bool additional { get; set; }
    public virtual bool is_locked { get; set; }
    public virtual bool is_initial_demand_editable { get; set; }
    public virtual bool is_quantity_done_editable { get; set; }
    public virtual string reference { get; set; }
    public virtual long move_lines_count { get; set; }
    public virtual object package_level_id { get; set; }
    public virtual bool picking_type_entire_packs { get; set; }
    public virtual bool display_assign_serial { get; set; }
    public virtual bool display_import_lot { get; set; }
    public virtual string next_serial { get; set; }
    public virtual long next_serial_count { get; set; }
    public virtual object orderpoint_id { get; set; }
    public virtual double forecast_availability { get; set; }
    public virtual string forecast_expected_date { get; set; }
    public virtual long[] lot_ids { get; set; }
    public virtual string reservation_date { get; set; }
    public virtual object product_packaging_id { get; set; }
    public virtual double product_packaging_qty { get; set; }
    public virtual double product_packaging_quantity { get; set; }
    public virtual bool show_quant { get; set; }
    public virtual bool show_lots_m2o { get; set; }
    public virtual bool show_lots_text { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual bool to_refund { get; set; }
    public virtual long[] account_move_ids { get; set; }
    public virtual long[] stock_valuation_layer_ids { get; set; }
    public virtual long[] analytic_account_line_ids { get; set; }
    public virtual object sale_line_id { get; set; }
}