namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class SurveySurvey
{
    public virtual long[] activity_ids { get; set; }
    public virtual string activity_state { get; set; }
    public virtual object activity_user_id { get; set; }
    public virtual object activity_type_id { get; set; }
    public virtual string activity_type_icon { get; set; }
    public virtual string activity_date_deadline { get; set; }
    public virtual string my_activity_date_deadline { get; set; }
    public virtual string activity_summary { get; set; }
    public virtual string activity_exception_decoration { get; set; }
    public virtual string activity_exception_icon { get; set; }
    public virtual object activity_calendar_event_id { get; set; }
    public virtual bool message_is_follower { get; set; }
    public virtual long[] message_follower_ids { get; set; }
    public virtual long[] message_partner_ids { get; set; }
    public virtual long[] message_ids { get; set; }
    public virtual bool has_message { get; set; }
    public virtual bool message_needaction { get; set; }
    public virtual long message_needaction_counter { get; set; }
    public virtual bool message_has_error { get; set; }
    public virtual long message_has_error_counter { get; set; }
    public virtual long message_attachment_count { get; set; }
    public virtual long[] rating_ids { get; set; }
    public virtual long[] website_message_ids { get; set; }
    public virtual bool message_has_sms_error { get; set; }
    public virtual string survey_type { get; set; }
    public virtual string allowed_survey_types { get; set; }
    public virtual string title { get; set; }
    public virtual long color { get; set; }
    public virtual string description { get; set; }
    public virtual string description_done { get; set; }
    public virtual string background_image { get; set; }
    public virtual string background_image_url { get; set; }
    public virtual bool active { get; set; }
    public virtual object user_id { get; set; }
    public virtual long[] restrict_user_ids { get; set; }
    public virtual long[] question_and_page_ids { get; set; }
    public virtual long[] page_ids { get; set; }
    public virtual long[] question_ids { get; set; }
    public virtual long question_count { get; set; }
    public virtual string questions_layout { get; set; }
    public virtual string questions_selection { get; set; }
    public virtual string progression_mode { get; set; }
    public virtual long[] user_input_ids { get; set; }
    public virtual string access_mode { get; set; }
    public virtual string access_token { get; set; }
    public virtual bool users_login_required { get; set; }
    public virtual bool users_can_go_back { get; set; }
    public virtual bool users_can_signup { get; set; }
    public virtual long answer_count { get; set; }
    public virtual long answer_done_count { get; set; }
    public virtual double answer_score_avg { get; set; }
    public virtual double answer_duration_avg { get; set; }
    public virtual long success_count { get; set; }
    public virtual long success_ratio { get; set; }
    public virtual string scoring_type { get; set; }
    public virtual double scoring_success_min { get; set; }
    public virtual double scoring_max_obtainable { get; set; }
    public virtual bool is_attempts_limited { get; set; }
    public virtual long attempts_limit { get; set; }
    public virtual bool is_time_limited { get; set; }
    public virtual double time_limit { get; set; }
    public virtual bool certification { get; set; }
    public virtual object certification_mail_template_id { get; set; }
    public virtual string certification_report_layout { get; set; }
    public virtual bool certification_give_badge { get; set; }
    public virtual object certification_badge_id { get; set; }
    public virtual object certification_badge_id_dummy { get; set; }
    public virtual bool session_available { get; set; }
    public virtual string session_state { get; set; }
    public virtual string session_code { get; set; }
    public virtual string session_link { get; set; }
    public virtual object session_question_id { get; set; }
    public virtual string session_start_time { get; set; }
    public virtual string session_question_start_time { get; set; }
    public virtual long session_answer_count { get; set; }
    public virtual long session_question_answer_count { get; set; }
    public virtual bool session_show_leaderboard { get; set; }
    public virtual bool session_speed_rating { get; set; }
    public virtual long session_speed_rating_time_limit { get; set; }
    public virtual bool has_conditional_questions { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual long[] slide_ids { get; set; }
    public virtual long[] slide_channel_ids { get; set; }
    public virtual long slide_channel_count { get; set; }
}