namespace OdooRpc.CoreCLR.Client.V8.Models;

public partial class Website
{
    public virtual string name { get; set; }
    public virtual long sequence { get; set; }
    public virtual string domain { get; set; }
    public virtual object company_id { get; set; }
    public virtual long[] language_ids { get; set; }
    public virtual long language_count { get; set; }
    public virtual object default_lang_id { get; set; }
    public virtual bool auto_redirect_lang { get; set; }
    public virtual bool cookies_bar { get; set; }
    public virtual bool configurator_done { get; set; }
    public virtual string logo { get; set; }
    public virtual string social_twitter { get; set; }
    public virtual string social_facebook { get; set; }
    public virtual string social_github { get; set; }
    public virtual string social_linkedin { get; set; }
    public virtual string social_youtube { get; set; }
    public virtual string social_instagram { get; set; }
    public virtual string social_tiktok { get; set; }
    public virtual string social_default_image { get; set; }
    public virtual bool has_social_default_image { get; set; }
    public virtual string google_analytics_key { get; set; }
    public virtual string google_search_console { get; set; }
    public virtual string google_maps_api_key { get; set; }
    public virtual string plausible_shared_key { get; set; }
    public virtual string plausible_site { get; set; }
    public virtual object user_id { get; set; }
    public virtual bool cdn_activated { get; set; }
    public virtual string cdn_url { get; set; }
    public virtual string cdn_filters { get; set; }
    public virtual object partner_id { get; set; }
    public virtual object menu_id { get; set; }
    public virtual string homepage_url { get; set; }
    public virtual string custom_code_head { get; set; }
    public virtual string custom_code_footer { get; set; }
    public virtual string robots_txt { get; set; }
    public virtual string favicon { get; set; }
    public virtual object theme_id { get; set; }
    public virtual bool specific_user_account { get; set; }
    public virtual string auth_signup_uninvited { get; set; }
    public virtual long id { get; set; }
    public virtual string display_name { get; set; }
    public virtual object create_uid { get; set; }
    public virtual string create_date { get; set; }
    public virtual object write_uid { get; set; }
    public virtual string write_date { get; set; }
    public virtual object channel_id { get; set; }
    public virtual long karma_profile_min { get; set; }
    public virtual string website_slide_google_app_key { get; set; }
    public virtual bool enabled_portal_reorder_button { get; set; }
    public virtual object salesperson_id { get; set; }
    public virtual object salesteam_id { get; set; }
    public virtual string show_line_subtotals_tax_selection { get; set; }
    public virtual string add_to_cart_action { get; set; }
    public virtual string account_on_checkout { get; set; }
    public virtual object cart_recovery_mail_template_id { get; set; }
    public virtual string contact_us_button_url { get; set; }
    public virtual double cart_abandoned_delay { get; set; }
    public virtual bool send_abandoned_cart_email { get; set; }
    public virtual long shop_ppg { get; set; }
    public virtual long shop_ppr { get; set; }
    public virtual string shop_default_sort { get; set; }
    public virtual long[] shop_extra_field_ids { get; set; }
    public virtual string product_page_image_layout { get; set; }
    public virtual string product_page_image_width { get; set; }
    public virtual string product_page_image_spacing { get; set; }
    public virtual long product_page_grid_columns { get; set; }
    public virtual bool prevent_zero_price_sale { get; set; }
    public virtual string prevent_zero_price_sale_text { get; set; }
    public virtual bool enabled_delivery { get; set; }
    public virtual object fiscal_position_id { get; set; }
    public virtual object pricelist_id { get; set; }
    public virtual object currency_id { get; set; }
    public virtual long[] pricelist_ids { get; set; }
    public virtual long[] all_pricelist_ids { get; set; }
}